// frontend/src/routes/admin/events/create.tsx
import { APIError } from '@/lib/api'
import EventForm from '@/lib/components/event-form/event-form'
import { useToast } from '@/lib/context/toast'
import { createEvent, createEventForm } from '@/lib/features/event'
import { useArtists, useVenues } from '@/lib/features/hook'
import { createFileRoute, useNavigate } from '@tanstack/react-router'
import type { z } from 'zod'

export const Route = createFileRoute('/admin/events/create')({
  component: RouteComponent,
})

function RouteComponent() {
  const { addToast } = useToast()
  const navigate = useNavigate()

  const artistQuery = useArtists()
  const venueQuery = useVenues()

  const isLoading = artistQuery.isLoading || venueQuery.isLoading
  const isError = artistQuery.isError || venueQuery.isError

  if (isLoading) return <p>Loading...</p>
  if (isError) return <p>Error...</p>

  const onSubmit = async (form: z.infer<typeof createEventForm>) => {
    try {
      await createEvent(form)
      addToast("Event tilføjet")
      navigate({ to: "/admin/events" })
    } catch (e) {
      console.error(e)
      if (e instanceof APIError) {
        addToast("Noget gik galt...", e.message, "error")
      }
    }
  }

  return (
    <EventForm
      venues={venueQuery.data?.records || []}
      artists={artistQuery.data?.records || []}
      disabled={false}
      onSubmit={onSubmit}
    />
  )
}

// frontend/src/routes/admin/events/create/+page.svelte
<script lang="ts">
	import { createEvent, createEventForm } from '$lib/features/event/event';
	import { z, ZodError } from 'zod';
	import EventForm from '../EventForm.svelte';
	import { toaster } from '$lib/toaster.svelte';
	import { goto } from '$app/navigation';

	let { data } = $props();

	let errors = $state<z.typeToFlattenedError<z.infer<typeof createEventForm>> | undefined>();
	let loading = $state(false);

	const handleSubmit = async (form: z.infer<typeof createEventForm>) => {
		try {
			loading = true;
			await createEvent(fetch, form);
			toaster.addToast('Event skabt', 'Event blev skabt fejlfrit');
			goto('/admin/events');
			loading = false;
		} catch (e) {
			if (e instanceof ZodError) {
				errors = e.flatten();
				loading = false;
				return;
			}
			loading = false;
			toaster.addToast('Event kunne ikke skabes', 'Der skete en fejl', 'error');
			throw e;
		}
	};
</script>

<main class="px-8 py-16 md:px-16">
	<EventForm
		{loading}
		venues={data.venues}
		artists={data.artists}
		{errors}
		onSubmit={handleSubmit}
	/>
</main>
