// frontend/src/routes/index.tsx
import { createFileRoute } from '@tanstack/react-router'
import { useEffect, type HTMLAttributes } from 'react';
import { useSuspenseQuery } from '@tanstack/react-query';
import { upcomingEventsQueryOpts } from '@/lib/features/events/query';
import { membersQueryOpts } from '@/lib/features/auth/query';
import { useMousePos } from '@/lib/hooks/useMousePos';
import { useRandom } from '@/lib/hooks/useRandom';
import { cn } from '@/lib/clsx';

import Posten from "@/lib/assets/sponsors/posten-logo.svg"
import StormsPakhus from "@/lib/assets/sponsors/storms-pakhus-logo.svg"
import UngOdense from "@/lib/assets/sponsors/ungodense-logo.svg"
import OdenseKommune from "@/lib/assets/sponsors/odense-kommune-logo.svg"
import SpillestedetOdense from "@/lib/assets/sponsors/spillestedet-odense-logo.svg"
import Kulturmaskinen from "@/lib/assets/sponsors/kulturmaskinen-logo.svg"
import Noctivaga from "@/lib/assets/sponsors/noctivaga-logo.svg"

import GlowingCursor from '@/lib/components/glowing-cursor';
import SlideshowGallery from '@/lib/components/slideshow-gallery';
import LinkButton from '@/lib/components/ui/button/link-button';
import LogoDisplay from '@/lib/components/logo-display';
import TeamDisplay from '@/lib/components/member-display';
import EventCard from '@/lib/features/events/components/event-card';

export const Route = createFileRoute('/')({
	component: App,
	loader: async ({ context: { queryClient } }) => {
		queryClient.ensureQueryData(upcomingEventsQueryOpts())
		queryClient.ensureQueryData(membersQueryOpts())
	}
})

const images: string[] = [...Array(5)].map((_, i) => `https://picsum.photos/seed/image-${i}/4096`)

function App() {
	const { data: { records: upcomingEvents } } = useSuspenseQuery(upcomingEventsQueryOpts())
	const { data: { records: members } } = useSuspenseQuery(membersQueryOpts())

	const { index: imgIdx, randomize } = useRandom(images)
	const mousePos = useMousePos()

	useEffect(() => {
		const interval = setInterval(() => randomize(), 5000)
		return () => clearInterval(interval)
	}, [])

	return (
		<main>
			<section className='relative isolate px-responsive flex flex-col justify-center gap-4 h-svh overflow-hidden'>
				{images.map((src, idx) => (
					<img key={src} src={src} className={cn('h-full w-full z-0 absolute top-0 left-0 brightness-40 object-cover opacity-0 transition-opacity duration-2000 [.active]:opacity-100', idx === imgIdx && "active")} />
				))}

				<GlowingCursor size="xl" mousePos={mousePos} />

				<div className='z-10 flex flex-col gap-16'>
					<div>
						<h1 className='text-5xl text-heading font-heading mb-4'>
							<b>Fynsk musik</b> med<br />
							fremtiden for øje
						</h1>
						<p className='max-w-md text-heading/75'>
							Et springbræt for unge, aspirerende musiskere, og en indgang ind til
							den danske musikscene.
						</p>
					</div>

					<div className='flex flex-col gap-4 sm:flex-row sm:w-fit'>
						<LinkButton to="/about-us" variant='secondary'>Læs mere</LinkButton>
						<LinkButton to="/events" variant='primary'>Find billetter</LinkButton>
					</div>
				</div>
			</section>

			{/* MISSION STATEMENT  */}
			<InfoSection className="paragraphs-relaxed">
				<h2 className='text-2xl font-semibold mb-4 text-heading font-heading'>Vores mission</h2>
				<p className='leading-relaxed'>
					Konnekt er en ungedrevet forening og et koncertinitiativ, der arbejder
					for at give unge musikere mulighed for at komme på scenen og få
					kontakt til et publikum. Vi arrangerer koncerter, hvor nye artister
					spiller sammen med mere etablerede upcoming-navne, og hvor publikum
					får adgang til musik, de ellers ikke ville have mødt.
				</p>
				<p>
					Men Konnekt handler ikke kun om musik – det handler om fællesskab og
					deltagelse. Vi skaber rum for unge, der vil være med som frivillige,
					arrangører eller idéfolk, og vi samarbejder med lokale aktører for at
					skabe synlighed, netværk og udvikling i Odenses kulturliv.
				</p>
				<p>
					Hos os er alle med til at forme oplevelsen – både på og bag scenen.
				</p>
			</InfoSection>

			{/* SPONSOR DISPLAY */}
			<InfoSection>
				<h3 className='text-center mb-4 text-text/75'>I samarbejde med</h3>
				<LogoDisplay
					srcs={[
						{ name: "Posten", href: "https://postenlive.dk", src: Posten },
						{ name: "Storms Pakhus", href: "https://stormspakhus.dk", src: StormsPakhus },
						{ name: "UngOdense", href: "https://ungodense.dk", src: UngOdense },
						{ name: "Odense Kommune", href: "https://odense.dk", src: OdenseKommune },
						{ name: "Spillestedet Odense", href: "https://ungodense.dk/index.php?open=1283&menu_id=58", src: SpillestedetOdense },
						{ name: "Kulturmaskinen", href: "https://kulturmaskinen.dk", src: Kulturmaskinen },
						{ name: "Noctivata", href: "https://noctivaga.dk", src: Noctivaga },
					]} />
			</InfoSection>

			{/* TEAM DISPLAY */}
			<InfoSection>
				<h2 className='text-4xl font-heading font-semibold text-heading mb-12 text-center'>Mød holdet</h2>
				<TeamDisplay members={members} />
			</InfoSection>

			{/* UPCOMING EVENTS DISPLAY */}
			{upcomingEvents.length > 0 && (
				<InfoSection>
					<h2 className="text-4xl font-heading font-semibold text-heading mb-8">Ses vi her?</h2>
					<SlideshowGallery>
						{upcomingEvents.map(event => <EventCard key={event.id} event={event} />)}
					</SlideshowGallery>
				</InfoSection>
			)}
		</main >
	)
}

const InfoSection = ({ children, className, ...rest }: HTMLAttributes<HTMLDivElement>) => (
	<section {...rest} className={cn("bg-background px-responsive py-16 first:pt-32 last:pb-32", className)}>
		{children}
	</section>
)

// frontend/src/routes/+page.svelte
<script lang="ts">
	import OdenseKommuneLogo from "$lib/assets/logos/odense-kommune-logo.svg";
	import UngOdenseLogo from "$lib/assets/logos/ungodense-logo.svg";
	import PostenLogo from "$lib/assets/logos/posten-logo.svg";
	import KulturMaskinenLogo from "$lib/assets/logos/kulturmaskinen-logo.svg";
	import SpillestedetOdenseLogo from "$lib/assets/logos/spillestedet-odense-logo.svg";
	import StormsPakhusLogo from "$lib/assets/logos/storms-pakhus-logo.svg";
	import NoctivagaLogo from "$lib/assets/logos/noctivaga-logo.svg";
	import GlowCursor from "$lib/components/GlowCursor.svelte";
	import { Randomiser } from "$lib/random.svelte";
	import Button from "$lib/components/ui/Button.svelte";
	import SponsorDisplay from "$lib/components/SponsorDisplay.svelte";
	import EventGrid from "$lib/features/events/components/EventGrid.svelte";
	import { getLandingImages } from "$lib/features/content/landing.remote.js";
	import { getUpcomingEvents } from "$lib/features/events/event.remote.js";
	import MemberDisplay from "$lib/components/MemberDisplay.svelte";
	import { getMembers } from "$lib/features/auth/auth.remote";

	const { items: landingImages } = await getLandingImages(undefined);
	const { items: upcomingEvents } = await getUpcomingEvents(undefined);
	const { items: members } = await getMembers(undefined);

	const randomiser = new Randomiser(landingImages);

	$effect(() => {
		const interval = setInterval(() => {
			randomiser.randomise();
		}, 3000);

		return () => clearInterval(interval);
	});
</script>

<svelte:head>
	<title>Konnekt | Forside</title>
	<meta title="description" content="Her kan du finde kommende events, aktuelle kunstnere mm." />
</svelte:head>

<section class="-z-50 mx-responsive flex h-svh flex-col justify-center gap-16">
	<div
		class="pointer-events-none absolute top-0 left-0 isolate -z-10 h-full w-full overflow-hidden"
	>
		<div class="absolute h-full w-full">
			<GlowCursor class="z-10" />
			{#each landingImages as { image: src, id }, i}
				<img
					{src}
					alt="Baggrundsbillede {i}"
					class={[
						"absolute z-0 h-full w-full object-cover brightness-70 transition-[opacity,scale] duration-500",
						randomiser.entry?.id === id ? "scale-100 opacity-100" : "scale-102 opacity-0"
					]}
				/>
			{/each}
		</div>
	</div>
	<section class="flex max-w-lg flex-col gap-16 overflow-hidden">
		<div class="flex flex-col">
			<h2
				class="font-heading mb-6 text-4xl leading-[1.2] text-text-light text-shadow-lg/15 sm:text-5xl"
			>
				<b>Fynsk musik</b> med fremtiden for øje
			</h2>
			<p class="text-text/75 leading-relaxed text-shadow-md">
				Et springbræt for unge, aspirerende musiskere, og en indgang ind til den danske musikscene.
			</p>
		</div>

		<div class="z-10 flex w-full flex-col-reverse gap-2 sm:flex-row">
			<Button href="/about" variant="secondary" class="w-full sm:w-fit">Læs mere</Button>
			<Button
				href={upcomingEvents.length > 0 ? "/events" : "/artists"}
				class="group w-full items-center gap-2 sm:w-fit"
			>
				{#if upcomingEvents.length > 0}
					Se events
				{:else}
					Se kunstnere
				{/if}
				<!-- <FaArrowRight class="text-sm transition-transform group-hover:translate-x-1" /> -->
			</Button>
		</div>
	</section>
	<!-- <Fader direction="up" class="absolute z-0 h-64 from-black/75" /> -->
</section>

<section class="border-t border-t-zinc-900 bg-zinc-950">
	<section class="mx-responsive flex flex-col gap-32 py-16">
		<section>
			<h1 class="font-heading mb-8 text-2xl font-bold">Vores mission</h1>
			<p class="text-text/75 leading-loose">
				Konnekt er en ungedrevet forening og et koncertinitiativ, der arbejder for at give unge
				musikere mulighed for at komme på scenen og få kontakt til et publikum. Vi arrangerer
				koncerter, hvor nye artister spiller sammen med mere etablerede upcoming-navne, og hvor
				publikum får adgang til musik, de ellers ikke ville have mødt.
				<br />
				<br />
				Men Konnekt handler ikke kun om musik – det handler om fællesskab og deltagelse. Vi skaber rum
				for unge, der vil være med som frivillige, arrangører eller idéfolk, og vi samarbejder med lokale
				aktører for at skabe synlighed, netværk og udvikling i Odenses kulturliv.
				<br />
				<br />
				Hos os er alle med til at forme oplevelsen – både på og bag scenen.
			</p>
		</section>

		<section class="z-0 flex w-full flex-col gap-8">
			<span class="text-text/50 text-center">I samarbejde med</span>
			<div class="relative isolate w-full">
				<SponsorDisplay
					srcs={[
						{ href: "https://postenlive.dk/", src: PostenLogo, title: "Posten" },
						{ href: "https://stormspakhus.dk/", src: StormsPakhusLogo, title: "Storms Pakhus" },
						{ href: "https://ungodense.dk/", src: UngOdenseLogo, title: "UngOdense" },
						{ href: "https://odense.dk", src: OdenseKommuneLogo, title: "Odense Kommune" },
						{
							href: "https://ungodense.dk/index.php?open=1283&menu_id=58",
							src: SpillestedetOdenseLogo,
							title: "Spillestedet"
						},
						{
							href: "https://kulturmaskinen.dk/",
							src: KulturMaskinenLogo,
							title: "Kulturmaskinen"
						},
						{ href: "https://www.noctivaga.dk/", src: NoctivagaLogo, title: "Noctivaga" }
					]}
				/>
			</div>
		</section>
		<section>
			<h1 class="font-heading mb-16 text-center text-4xl font-bold">Mød holdet</h1>
			<MemberDisplay {members} />
		</section>
		{#if upcomingEvents.length > 0}
			<section>
				<h1 class="font-heading mb-8 text-4xl font-bold">Ses vi her?</h1>
				<EventGrid events={upcomingEvents} />
			</section>
		{/if}
	</section>
</section>
