// frontend/src/routes/events/[id]/EventDetails.svelte
<script lang="ts">
	import MapIcon from '~icons/mdi/map-marker';
	import CalendarIcon from '~icons/mdi/calendar';
	import MusicIcon from '~icons/mdi/music';
	import GroupIcon from '~icons/mdi/account-group';
	import Button from '$lib/components/ui/Button.svelte';
	import { formatDateStr } from '$lib/time';
	import type { Event } from '$lib/event';
	import { earliestConcert } from '$lib/concert';

	type Props = {
		event: Event;
		active?: boolean;
	};

	let { event, active }: Props = $props();
	let fromDate = $derived(earliestConcert(event.concerts)?.from);

	let artistNames = $derived(event.concerts.map((concert) => concert.artist.name));
</script>

<div class="relative h-[calc((100vh/4)*3)] overflow-hidden">
	<img
		src={event?.imageUrl}
		alt={event?.title}
		class="absolute top-0 left-0 h-full w-full object-cover"
	/>
	<!-- FADER -->
	<!-- <Fader direction="to-bottom" /> -->
	<div class="px-auto absolute bottom-0 left-0 w-full space-y-2 px-12 pb-12">
		<h1 class="mb-8 w-full text-5xl font-bold md:text-8xl">{event?.title}</h1>
		<div class="flex w-full items-end gap-8">
			<div class="w-full space-y-1 text-zinc-300">
				<div class="flex items-center gap-2">
					<CalendarIcon />
					<span>{formatDateStr(fromDate || new Date())}</span>
				</div>
				<div class="flex items-center gap-2">
					<GroupIcon />
					<span>{artistNames.join(', ')}</span>
				</div>
				<div class="flex items-center gap-2">
					<MusicIcon />
					<span>{['EDM', 'Dance', 'House', "Drum'n'Bass"].join(', ')}</span>
				</div>
				<div class="flex items-center gap-2">
					<MapIcon />
					<span>{event.venue.name}, {event.venue.city}</span>
				</div>
			</div>
			<div class="w-96 space-y-2">
				<Button expandX expandY extraClass="h-18">Køb billet</Button>
				{#if !active}
					<Button type="secondary" expandX expandY extraClass="h-18">Læs mere</Button>
				{/if}
			</div>
		</div>
	</div>
</div>

// frontend/app/routes/events.$id/event-details.tsx
import { BiCalendar, BiMap, BiMusic } from "react-icons/bi"
import { EventDTO } from "@/lib/dto/event.dto"
import { formatDateString } from "@/lib/time"
import { cn } from "@/lib/utils";
import { Fader } from "@/components/ui/fader";

type Props = {
  isLoading: boolean;
  event: EventDTO | undefined
}

export const EventDetails = ({ event, isLoading }: Props) => {
  const { venue, fromDate } = event || {}

  if (isLoading) return <Skeleton />

  return (
    <div className="relative h-[calc((100vh/4)*3)] overflow-hidden">
      <img
        src={event?.coverImageUrl}
        alt={event?.title}
        className="absolute top-0 left-0 h-full w-full object-cover"
      />
      {/* FADER */}
      <Fader direction="to-bottom" />
      <div className="absolute bottom-0 left-0 pb-12 px-12 space-y-2">
        <h1 className={cn(
          "w-full text-5xl md:text-8xl font-bold mb-2",
        )}>{event?.title}</h1>
        <div className="flex gap-2 items-center">
          <BiMap />
          <span>{venue?.name}, {venue?.city}</span>
        </div>
        <div className="flex gap-2 items-center">
          <BiCalendar />
          <span>{formatDateString(fromDate || new Date())}</span>
        </div>
        <div className="flex gap-2 items-center">
          <BiMusic />
          <span>{event?.genres.join(", ")}</span>
        </div>
      </div>
    </div>
  )
}

const Skeleton = () => {
  return (
    <div className="relative h-[calc((100vh/4)*3)] overflow-hidden">
      {/* IMAGE */}
      <div className="absolute top-0 left-0 h-full w-full bg-background"></div>

      <Fader direction="to-bottom" />
      <div className="absolute bottom-0 left-0 px-12 pb-12 space-y-3 z-50">
        {/* TITLE */}
        <div className="w-[calc((100vw/3)*2)] h-16 mb-4 bg-zinc-900 rounded-md animate-pulse"></div>
        {/* VENUE */}
        <div className="flex gap-2 items-center animate-pulse">
          <div className="h-5 w-5 bg-zinc-900 rounded-full"></div>
          <div className="h-5 w-12 bg-zinc-900 rounded-md"></div>
          <div className="h-5 w-16 bg-zinc-900 rounded-md"></div>
        </div>
        {/* DATE */}
        <div className="flex gap-2 items-center animate-pulse">
          <div className="h-5 w-5 bg-zinc-900 rounded-full"></div>
          <div className="h-5 w-16 bg-zinc-900 rounded-md"></div>
          <div className="h-5 w-20 bg-zinc-900 rounded-md"></div>
        </div>
        {/* GENRES */}
        <div className="flex gap-2 items-center animate-pulse">
          <div className="h-5 w-5 bg-zinc-900 rounded-full"></div>
          <div className="h-5 w-12 bg-zinc-900 rounded-md"></div>
          <div className="h-5 w-10 bg-zinc-900 rounded-md"></div>
        </div>
      </div>
    </div>
  )
}
