// frontend/src/lib/components/event-details.tsx
import { DATE_FORMAT } from '@/lib/time';

import { format } from 'date-fns';

import { earliestConcert } from '@/lib/features/concert';
import type { Event } from '@/lib/features/event';

import Fader from "@/lib/components/fader"

import { FaCalendarDay, FaMapPin, FaMusic, FaTicketAlt } from "react-icons/fa"
import LinkButton from './ui/button/link-button';

type Props = {
	event: Event;
	active?: boolean;
	prefix?: string;
};

const EventDetails = ({ event, active, prefix }: Props) => {
	let fromDate = earliestConcert(event.concerts)?.from;

	let artists = event.concerts.map(({ artist }) => artist);

	// https://stackoverflow.com/questions/2218999/how-to-remove-all-duplicates-from-an-array-of-objects
	const genres = artists
		.flatMap((artist) => artist.genres)
		.filter((value, index, self) => index === self.findIndex((t) => t.id === value.id))
		.sort((a, b) => {
			const nameA = a.name.toUpperCase();
			const nameB = b.name.toUpperCase();

			return nameA < nameB ? -1 : nameA > nameB ? 1 : 0;
		})

	let genresString = genres.map((genre) => genre.name).join(', ')

	const locationUrl = new URL(
		`https://www.google.com/maps/search/?` +
		new URLSearchParams({
			api: '1',
			query: `${event.venue.name},${event.venue.city},${event.venue.countryCode}`
		})
	)

	return (
		<div className="relative isolate flex h-[calc((100svh/4)*3)] items-end overflow-hidden pb-8 sm:pb-16">
			<img
				src={event.imageUrl}
				alt="Event cover"
				className="absolute top-0 left-0 -z-10 h-full w-full object-cover brightness-50"
			/>

			<Fader className="absolute -z-10 h-1/2" direction="up" />

			<div className="px-auto flex w-full flex-col">
				{prefix && (
					<span>{prefix}</span>

				)}
				<h1 className="mb-8 text-7xl font-bold">{event.title}</h1>

				<div className="text-text/85 flex flex-col gap-8 sm:flex-row">
					<div className="flex flex-1 flex-col gap-2">
						{fromDate && (
							<div className="flex items-center gap-4">
								<FaCalendarDay />
								<span className="line-clamp-1">{format(fromDate, DATE_FORMAT)}</span>
							</div>
						)}
						<div className="flex items-center gap-4">
							<FaMapPin />
							<a className="line-clamp-1" href={locationUrl.toString()}
							>{event.venue.name}, {event.venue.city} ({event.venue.countryCode})</a
							>
						</div>
						<div className="flex items-center gap-4">
							<FaMusic />
							<span className="line-clamp-1">{genresString}</span>
						</div>
					</div>

					<div className="flex flex-col justify-end gap-2">
						<LinkButton to={event.ticketUrl} className="w-full"><FaTicketAlt />Køb billet</LinkButton>
						{!active && (
							<LinkButton
								to="/events/$eventId"
								params={{ eventId: event.id.toString() }}
								variant="outline"
								className="w-full"
							>
								Læs mere
							</LinkButton>
						)}
					</div>
				</div>
			</div>
		</div>
	)
}

export default EventDetails

// frontend/src/routes/(app)/events/[id]/EventDetails.svelte
<script lang="ts">
	import { DATE_FORMAT } from '$lib/time';

	import { format } from 'date-fns';

	import { earliestConcert } from '$lib/features/concert/concert';
	import type { Event } from '$lib/features/event/event';

	import Button from '$lib/components/ui/Button.svelte';
	import Fader from '$lib/components/Fader.svelte';

	import TicketIcon from '~icons/mdi/ticket-confirmation-outline';
	import MapIcon from '~icons/mdi/map-marker';
	import CalendarIcon from '~icons/mdi/calendar';
	import MusicIcon from '~icons/mdi/music';

	type Props = {
		event: Event;
		active?: boolean;
		prefix?: string;
	};

	let { event, active }: Props = $props();
	let fromDate = $derived(earliestConcert(event.concerts)?.from);

	let artists = $derived(event.concerts.map(({ artist }) => artist));

	// https://stackoverflow.com/questions/2218999/how-to-remove-all-duplicates-from-an-array-of-objects
	const genres = $derived(
		artists
			.flatMap((artist) => artist.genres)
			.filter((value, index, self) => index === self.findIndex((t) => t.id === value.id))
			.sort((a, b) => {
				const nameA = a.name.toUpperCase();
				const nameB = b.name.toUpperCase();

				return nameA < nameB ? -1 : nameA > nameB ? 1 : 0;
			})
	);

	let genresString = $derived(genres.map((genre) => genre.name).join(', '));

	const locationUrl = $derived(
		new URL(
			`https://www.google.com/maps/search/?` +
				new URLSearchParams({
					api: '1',
					query: `${event.venue.name},${event.venue.city},${event.venue.countryCode}`
				})
		)
	);
</script>

<div class="relative isolate flex h-[calc((100svh/4)*3)] items-end overflow-hidden pb-8 sm:pb-16">
	<img
		src={event.imageUrl}
		alt="Event cover"
		class="absolute top-0 left-0 -z-10 h-full w-full object-cover brightness-50"
	/>

	<Fader class="absolute -z-10 h-1/2" direction="up" />

	<div class="px-auto flex w-full flex-col">
		<h1 class="mb-8 text-7xl font-bold">{event.title}</h1>

		<div class="text-text/85 flex flex-col gap-8 sm:flex-row">
			<div class="flex flex-1 flex-col gap-1">
				{#if fromDate}
					<div class="flex items-center gap-4">
						<CalendarIcon />
						<span>{format(fromDate, DATE_FORMAT)}</span>
					</div>
				{/if}
				<div class="flex items-center gap-4">
					<MapIcon />
					<a href={locationUrl.toString()}
						>{event.venue.name}, {event.venue.city} ({event.venue.countryCode})</a
					>
				</div>
				<div class="flex items-center gap-4">
					<MusicIcon />
					<span>{genresString}</span>
				</div>
			</div>

			<div class="flex flex-col justify-end gap-2">
				<Button href={event.ticketUrl} class="w-full"><TicketIcon />Køb billet</Button>
				{#if !active}
					<Button href="/events/{event.id}" variant="outline" class="w-full">Læs mere</Button>
				{/if}
			</div>
		</div>
	</div>
</div>
