// frontend/src/lib/components/footer/footer.tsx
import { Link } from "@tanstack/react-router"

const Footer = () => (
	<footer className='flex flex-col gap-8 px-responsive py-12 border-t border-t-zinc-900'>
		<div className="grid grid-cols-1 sm:grid-cols-2 gap-8">
			<section>
				<h3 className="font-heading text-heading font-semibold mb-4">Find rundt</h3>
				<ul>
					<li><Link to="/">Hjem</Link></li>
					<li><Link to="/events">Events</Link></li>
					<li><Link to="/artists">Kunstnere</Link></li>
					<li><Link to="/about-ut">Om os</Link></li>
				</ul>
			</section>

			<section className="flex flex-col sm:items-end">
				<span className="font-bold mb-4 text-heading">Logo</span>
				<ul className="flex flex-col sm:items-end">
					<li><a href="mailto:konnekt.samarbejde@gmail.com">konnekt.samarbejde@gmail.com</a></li>
					<li><a href="mailto:booking.konnekt@gmail.com">booking.konnekt@gmail.com</a></li>
				</ul>
			</section>
		</div>

		<p className="text-center text-sm">&copy;&nbsp;{new Date().getFullYear()}&nbsp;Foreningen Konnekt</p>
	</footer>
)

export default Footer

// frontend/src/routes/(app)/Footer.svelte
<script lang="ts">
	import Logo from '$lib/assets/Logo.svelte';
</script>

<footer class="px-auto border-t border-t-zinc-900 bg-zinc-950 pt-8 pb-6">
	<div class="mb-8 grid w-full grid-cols-1 sm:grid-cols-2">
		<!-- NAVIGATION -->
		<div class="flex-1">
			<h3 class="font-heading mb-2 font-bold">Find rundt.</h3>
			<ul class="text-text/50">
				<li><a href="/">Hjem</a></li>
				<li><a href="/events">Events</a></li>
				<li><a href="/artists">Kunstnere</a></li>
				<li><a href="/om-os">Om os</a></li>
			</ul>
		</div>
		<!-- CONTACT INFORMATION -->
		<div class="flex flex-1 flex-col items-end">
			<Logo class="mb-2 h-4" />
			<address class="not-italic">
				<ul class="text-text/50 flex flex-col items-end">
					<a href="tel:+4512345678">+45 12 34 56 78</a>
					<a href="mailto:konnekt@mail.dk">konnekt@mail.dk</a>
					<a href="https://google.maps.com/konnekt">Konnektvej 17B, Konnekticut</a>
				</ul>
			</address>
		</div>
	</div>
	<div class="text-text/50 flex justify-center text-xs">
		<span>&copy;&nbsp;{new Date().getFullYear()}&nbsp;Foreningen&nbsp;KONNEKT&reg;</span>
	</div>
</footer>
