// frontend/src/lib/features/events/components/event-calendar.tsx
import { addHours, differenceInHours, differenceInMinutes, format } from "date-fns"
import type { Concert, Event } from "../event"
import { DATE_FORMAT } from "@/lib/date"
import { createContext, useContext } from "react"
import { Link } from "@tanstack/react-router"
import { cn } from "@/lib/clsx"
import LinkButton from "@/lib/components/ui/button/link-button"
import { generateGoogleCalendarEventUrl } from "@/lib/google-calendar"
import { FaCalendarPlus } from "react-icons/fa6"

type Props = {
	event: Event
}

type EventCalendarContext = {
	timelineStart: Date
	timelineEnd: Date
	timelineTotalMins: number;
}

const EventCalendarContext = createContext<EventCalendarContext | null>(null)

const useEventCalendarContext = () => {
	const ctx = useContext(EventCalendarContext)
	if (!ctx) throw new Error("No EventCalendarContext.Provider found")
	return ctx
}

const formatConcertDuration = (from: Date, to: Date) => {
	return `${format(from, "HH:mm")} - ${format(to, "HH:mm")}`
}

const padHour = (hour: number) => {
	return String(hour).padStart(2, "0")
}

const EventCalendar = ({ event }: Props) => {
	const firstConcert = event.concerts[0]
	const lastConcert = event.concerts[event.concerts.length - 1]

	const timelineStart = firstConcert.from.getMinutes() > 0 ? addHours(firstConcert.from, - 1) : firstConcert.from
	const timelineEnd = lastConcert.to.getMinutes() > 0 ? addHours(lastConcert.to, 1) : lastConcert.to
	const timelineTotalMins = differenceInMinutes(timelineEnd, timelineStart)

	const googleCalendarUrl = generateGoogleCalendarEventUrl(event)

	return (
		<EventCalendarContext.Provider value={{ timelineStart, timelineEnd, timelineTotalMins }}>
			<div className="flex flex-col gap-16">
				<div className="flex justify-between">
					<div>
						<h2 className="text-xl font-semibold text-heading">Program for {event.title}</h2>
						<span>{format(firstConcert.from, DATE_FORMAT)}</span>
					</div>
					<LinkButton
						variant="secondary"
						to={googleCalendarUrl.toString()}
						className="hidden sm:flex w-fit h-fit"
					>
						<FaCalendarPlus />Føj til kalender
					</LinkButton>
				</div>
				<div className="grid grid-cols-[64px_auto] gap-4">
					<Timeline />
					<ul className="relative">
						{event.concerts.map((concert) => <ConcertEntry key={concert.id} concert={concert} />)}
					</ul>
				</div>
				<LinkButton
					variant="secondary"
					to={googleCalendarUrl.toString()}
					className="sm:hidden w-full h-fit"
				>
					<FaCalendarPlus />Føj til kalender
				</LinkButton>

			</div>
		</EventCalendarContext.Provider>
	)
}


const Timeline = () => {
	const { timelineStart, timelineEnd } = useEventCalendarContext()
	const displayHours = differenceInHours(timelineEnd, timelineStart)

	return (
		<div className="flex flex-col">
			{[...Array(displayHours)].map((_, i) => (
				<div key={i} className="border-t border-zinc-800 h-32">
					{padHour(timelineStart.getHours() + i)}:00
				</div>
			))}
		</div>
	)
}

type ConcertEntryProps = {
	concert: Concert
}

const ConcertEntry = ({ concert }: ConcertEntryProps) => {
	const { timelineStart, timelineTotalMins } = useEventCalendarContext()
	const offsetRatio = differenceInMinutes(concert.from, timelineStart) / timelineTotalMins
	const durationMinutes = differenceInMinutes(concert.to, concert.from)

	return (
		<li
			style={{ top: `calc(${offsetRatio} * 100%)`, height: `calc(${durationMinutes / timelineTotalMins} * 100%)` }}
			className="group absolute w-full">
			<Link
				to="/artists/$artistId"
				params={{ artistId: concert.artist.id.toString() }}
				className={cn(
					"px-3 py-2 h-full flex justify-between bg-blue-950 border border-blue-900 rounded-sm transition-colors",
					"hover:bg-blue-900 hover:border-blue-700"
				)}
			>
				<span className="font-semibold text-blue-300 group-hover:underline">{concert.artist.name}</span>
				<span className="text-blue-400">{formatConcertDuration(concert.from, concert.to)}</span>
			</Link>
		</li>
	)
}

export default EventCalendar

// frontend/src/lib/features/events/components/EventCalendar.svelte
<script lang="ts">
	import type { Concert, Event } from "$lib/features/events/event";
	import { addHours, differenceInMinutes, format, startOfHour } from "date-fns";
	import Button from "../../../components/ui/Button.svelte";
	import { generateGoogleCalendarEventUrl } from "$lib/google-calendar";

	type Props = {
		event: Event;
	};

	let { event }: Props = $props();

	const calendarUrl = $derived(generateGoogleCalendarEventUrl(event));

	let startHourDate = $derived(
		event.concerts.length > 0 ? startOfHour(event.concerts[0].fromDate) : startOfHour(new Date())
	);

	let endHour = $derived(
		event.concerts.length > 0
			? addHours(startOfHour(event.concerts[event.concerts.length - 1].toDate), 1)
			: addHours(startOfHour(new Date()), 4)
	);

	let timeMarkers = $derived.by(() => {
		let markers: Date[] = [];
		let current = startHourDate;

		while (current <= endHour) {
			markers = [...markers, current];
			current = addHours(current, 1);
		}

		return markers;
	});

	let totalMinutes = $derived(Math.max(1, differenceInMinutes(endHour, startHourDate)));
</script>

{#snippet entry(concert: Concert)}
	{@const concertStartOffset = differenceInMinutes(concert.fromDate, startHourDate)}
	{@const concertDurationMinutes = differenceInMinutes(concert.toDate, concert.fromDate)}

	<a
		style:top="calc({concertStartOffset / totalMinutes} * 100%)"
		style:height="calc({concertDurationMinutes / totalMinutes} * 100% - 1px)"
		class="group absolute flex min-h-10 w-full justify-between overflow-hidden rounded-xl border border-t border-blue-800 bg-blue-950 p-4 text-sm transition-colors hover:border-blue-600 hover:bg-blue-900"
		href="/artists/{concert.artist.id}"
	>
		<p class="font-bold text-blue-200 group-hover:underline">
			{concert.artist.name}
		</p>
		<p class="text-blue-500">
			{format(concert.fromDate, "HH:mm")} - {format(concert.toDate, "HH:mm")}
		</p>
	</a>
{/snippet}

<div class="flex w-full flex-col gap-8">
	<div class="flex items-center-safe justify-between">
		{#if event.concerts.length > 0}
			<div>
				<h3 class="mb-2 text-xl font-bold text-text-light">
					Program for {event.title}
				</h3>
				<span>{format(event.concerts[0].fromDate, "EEEE, dd/MM/yyyy")}</span>
			</div>
		{/if}

		{#if calendarUrl}
			<Button
				class="hidden sm:flex"
				variant="secondary"
				href={calendarUrl.toString()}
				target="__blank"
			>
				<!-- <FaCalendarPlus /> -->
				Føj til kalender
			</Button>
		{/if}
	</div>

	<div class="overflow-y-scroll">
		<div class="grid h-full min-h-72 flex-1 gap-4 sm:grid-cols-[48px_1fr]">
			<!-- {/*  Timeline */} -->
			<div class="relative hidden sm:block">
				{#each timeMarkers as marker, i}
					{@const markerOffset = differenceInMinutes(marker, startHourDate)}

					<div
						style:top="calc({markerOffset / totalMinutes} * 100%)"
						class={[
							"absolute w-full flex-col gap-1 text-sm",
							i === timeMarkers.length - 1 ? "hidden" : "flex"
						]}
					>
						<div class="h-px w-full bg-zinc-800"></div>
						<span>{format(marker, "HH:mm")}</span>
					</div>
				{/each}
			</div>

			<!-- {/* Events */} -->
			<div class="relative">
				{#each event.concerts as concert}
					{@render entry(concert)}
				{/each}
			</div>
		</div>

		{#if calendarUrl}
			<Button
				class="flex w-full sm:hidden"
				variant="secondary"
				href={calendarUrl.toString()}
				target="__blank"
			>
				<!-- <FaCalendarPlus /> -->
				Føj til kalender
			</Button>
		{/if}
	</div>
</div>
