// frontend/src/lib/features/event/components/event-form/event-form.tsx
import { Controller, FormProvider, useFieldArray, useForm, type UseFieldArrayReturn, type UseFormReturn } from "react-hook-form"
import { zodResolver } from "@hookform/resolvers/zod"
import { FaArrowsRotate, FaPlus, FaUpload } from "react-icons/fa6"
import { addMinutes, roundToNearestHours } from "date-fns"
import ConcertList from "./concert-list"
import { createEvent, eventForm, updateEvent, type Event, type EventFormValues } from "@/lib/features/event/event"
import type { Venue } from "@/lib/features/event/venue"
import type { Artist } from "@/lib/features/artist/artist"
import { createContext, useContext } from "react"
import FormField from "@/lib/components/form-field"
import ImagePreview from "@/lib/components/image-preview"
import Tiptap from "@/lib/components/tiptap/tiptap"
import Button from "@/lib/components/ui/button/button"
import Input from "@/lib/components/ui/input"
import Selector from "@/lib/components/ui/selector"
import LinkButton from "@/lib/components/ui/button/link-button"
import { createSubmitHandler } from "@/lib/api"
import { useQueryClient } from "@tanstack/react-query"
import { useAuth } from "@/lib/context/auth"

// We must include the fieldArray as part of the context, to not create another
// instance in children.
//
// This also means, that we are NOT to use the react-hook-form useFormContext,
// but rather the extended useEventFormContext!
type EventFormContext =
	UseFieldArrayReturn<EventFormValues> &
	UseFormReturn<EventFormValues> & {
		event?: Event;
		venues: Venue[]
		artists: Artist[]

		onAddConcert: () => void;
		onDeleteConcert: (index: number) => void
	}

const EventFormContext = createContext<EventFormContext | undefined>(undefined)

export const useEventFormContext = () => {
	const eventFormContext = useContext(EventFormContext)

	if (!eventFormContext) throw new Error("No provider for EventFormContext")

	return eventFormContext
}

type Props = {
	event?: Event;
	venues: Venue[]
	artists: Artist[]
}


const EventForm = ({ event, venues, artists }: Props) => {
	const { hasPermissions } = useAuth()
	const queryClient = useQueryClient()

	const isEditable = hasPermissions(["edit:event"])

	const methods = useForm({
		disabled: !isEditable,
		defaultValues:
			event ? {
				title: event.title,
				description: event.description,
				venueId: event?.venue.id,
				image: undefined,
				ticketUrl: event.ticketUrl,
				concerts: event?.concerts.map(c => ({
					from: c.from,
					to: c.to,
					artistID: c.artist.id,
				})),
				isPublic: event.isPublic
			} : {
				isPublic: true,
				venueId: venues.find(v => v.name === "Posten")?.id
			},
		resolver: zodResolver(eventForm),
	})

	const { control, formState: { errors }, setValue, getValues, handleSubmit } = methods;

	const fieldArrayMethods = useFieldArray({ control, name: "concerts" })
	const { fields, remove, append } = fieldArrayMethods


	const onAddConcert = () => {
		const prevEnd = fields.length > 0
			? getValues(`concerts.${fields.length - 1}.to`)
			: undefined

		const from = prevEnd ? addMinutes(prevEnd, 15) : roundToNearestHours(new Date())
		const to = addMinutes(from, 30)
		append({ artistID: 1, from, to })
	}

	const onDeleteConcert = (idx: number) => {
		remove(idx)
	}



	const onSubmit = createSubmitHandler({
		action: async (form: EventFormValues) => {
			event ? await updateEvent(form, event.id) : await createEvent(form)
			await queryClient.invalidateQueries({ queryKey: ["events"] })
		},
		successMessage: event ? "Event opdateret" : "Event skabt",
		errorMessage: event ? "Kunne ikke redigére event" : "Kunne ikke lave event",
		navigateTo: "/admin/events",
	})

	return (
		<FormProvider {...methods}>
			<EventFormContext.Provider value={{ ...methods, ...fieldArrayMethods, artists, venues, event, onAddConcert, onDeleteConcert }}>
				<form onSubmit={handleSubmit(onSubmit)} className="flex flex-col gap-16 @container">
					<FormField error={errors.image}>
						<ImagePreview disabled={!isEditable} src={event?.imageUrl} accept="image/jpeg,image/png" onChange={file => setValue("image", file)} />
					</FormField>

					<GeneralSection />

					<FormField error={errors.description}>
						<Controller
							control={control}
							name="description"
							render={({ field: { value, onChange } }) => (
								<Tiptap disabled={!isEditable} content={value} onChange={onChange} />
							)}
						/>
					</FormField>

					<ConcertsSection />

					{isEditable && (
						<Button className="w-full md:w-fit" type="submit"><FaUpload />Offentliggør</Button>
					)}
				</form>
			</EventFormContext.Provider>
		</FormProvider>
	)
}

const GeneralSection = () => {
	const { register, formState: { errors, disabled } } = useEventFormContext()
	const isEditable = !disabled

	return (
		<section>

			<h1 className="text-2xl font-heading font-bold mb-4">Generelt</h1>
			<div className="flex flex-col gap-4">
				<FormField error={errors.title}>
					<Input {...register("title")} placeholder="Eventtitel" />
				</FormField>

				<div className="flex flex-col @xl:flex-row gap-4">
					<FormField error={errors.ticketUrl}>
						<Input {...register("ticketUrl")} placeholder="Billet-URL" className="w-full" />
					</FormField>

					<VenueSelector />
				</div>
				{isEditable && (
					<FormField className="w-min">
						<label className="flex gap-2 items-center">
							<input type="checkbox" {...register("isPublic")} />
							Offentlig
						</label>
					</FormField>
				)}
			</div>
		</section>
	)
}

const ConcertsSection = () => {
	const { fields } = useEventFormContext()
	return (
		<section>
			<h1 className="text-2xl font-bold font-heading mb-4">Koncerter</h1>
			<ConcertList>
				{fields.map((field, index) => (
					<ConcertList.Entry key={field.id} index={index} />
				))}
			</ConcertList>
		</section>
	)
}

const VenueSelector = () => {
	const { venues, control, formState: { disabled } } = useEventFormContext()
	const isEditable = !disabled

	return (
		<Controller
			control={control}
			name="venueId"
			render={({ field: { onChange, ...rest }, fieldState: { error } }) => (
				<FormField error={error}>
					<Selector
						{...rest}
						onChange={e => onChange(parseInt(e.target.value))}
						placeholder="Vælg venue..."
						className="w-full"
					>
						{venues.map(({ id, name }) => <option key={id} value={id}>{name}</option>)}
					</Selector>

					{isEditable && (
						<div className="flex gap-2">
							<Button variant="ghost" className="aspect-square h-full">
								<FaArrowsRotate />
							</Button>
							<LinkButton to="/admin/venues/create" className="aspect-square h-full">
								<FaPlus />
							</LinkButton>
						</div>
					)}
				</FormField>
			)}
		/>
	)
}

export default EventForm

// frontend/src/lib/features/events/components/EventForm.svelte
<script lang="ts">
	import type { HTMLFormAttributes } from "svelte/elements";
	import FormField from "$lib/components/FormField.svelte";
	import ImagePreview from "$lib/components/ImagePreview.svelte";
	import Button from "$lib/components/ui/Button.svelte";
	import { createEvent, editEvent } from "../event.remote.ts";
	import type { Event } from "../event";
	import Input from "$lib/components/ui/Input.svelte";
	import { addMinutes, format, roundToNearestHours } from "date-fns";
	import { getArtists } from "../../artists/artist.remote.ts";
	import { INPUT_DATETIME_FORMAT } from "$lib/time";
	import Select from "$lib/components/ui/Select.svelte";
	import { getVenues } from "../../venues/venue.remote.ts";
	import Card from "$lib/components/Card.svelte";
	import { getToastContext } from "../../../components/toaster/toaster.svelte.ts";
	import { hasPermissions } from "../../../features/auth/auth.remote.ts";

	const DEFAULT_CHANGEOVER_MINUTES = 15;
	const DEFAULT_CONCERT_DURATION = 40;

	type CreateProps = {
		variant: "create";
		form: typeof createEvent;
		event?: never;
	};

	type EditProps = {
		variant: "edit";
		form: typeof editEvent;
		event: Event;
	};

	type Props = HTMLFormAttributes & (CreateProps | EditProps);

	let { ...rest }: Props = $props();

	let { title, description, cover, ticketUrl, venueId, isPublic } = rest.form.fields;

	const { items: artists } = $derived(await getArtists(undefined));
	const { items: venues } = $derived(await getVenues(undefined));

	const toaster = getToastContext();

	let coverInput = $state<HTMLInputElement>();

	const disabled = $derived(!(await hasPermissions(["events:edit"])));

	$effect(() => {
		if (rest.variant === "create") return;

		rest.form.fields.set({
			...rest.event,
			eventId: rest.event.id,
			cover: undefined,
			venueId: rest.event.venue.id,
			concerts: rest.event.concerts.map((concert) => ({
				id: concert.id,
				artistId: concert.artist.id,
				fromDate: format(concert.fromDate, INPUT_DATETIME_FORMAT),
				toDate: format(concert.toDate, INPUT_DATETIME_FORMAT)
			}))
		});
	});

	const addConcert = () => {
		const concertCount = rest.form.fields.concerts.value()?.length ?? 0;

		if (concertCount === 0) {
			const fromDate = roundToNearestHours(new Date());
			const toDate = addMinutes(fromDate, DEFAULT_CONCERT_DURATION);

			rest.form.fields.concerts[0].set({
				id: undefined,
				artistId: "",
				fromDate: format(fromDate, INPUT_DATETIME_FORMAT),
				toDate: format(toDate, INPUT_DATETIME_FORMAT)
			});

			return;
		}

		const lastConcert = rest.form.fields.concerts[concertCount - 1].value();

		const fromDate = addMinutes(lastConcert.toDate, DEFAULT_CHANGEOVER_MINUTES);
		const toDate = addMinutes(fromDate, DEFAULT_CONCERT_DURATION);

		rest.form.fields.concerts[concertCount].set({
			id: undefined,
			artistId: "",
			fromDate: format(fromDate, INPUT_DATETIME_FORMAT),
			toDate: format(toDate, INPUT_DATETIME_FORMAT)
		});
	};
</script>

<form
	{...rest.form.enhance(async ({ submit }) => {
		try {
			await submit();
		} catch (error) {
			console.error(error);
			toaster.add("Kunne ikke lave event", "dangerous");
		}
	})}
	enctype="multipart/form-data"
	class="flex flex-col"
>
	{#if rest.variant === "edit"}
		<input {...rest.form.fields.eventId.as("hidden", rest.event.id)} />
	{/if}

	<FormField issues={cover.issues()?.map((i) => i.message)} class="mb-16">
		<input
			bind:this={coverInput}
			{...rest.form.fields.cover.as("file")}
			class="hidden"
			{disabled}
		/>
		<ImagePreview src={cover.value() ? URL.createObjectURL(cover.value()) : rest.event?.cover} />
		{#if !disabled}
			<Button type="button" variant="secondary" onclick={() => coverInput?.click()}>Vælg...</Button>
		{/if}
	</FormField>

	<section class="mb-16">
		<h2 class="mb-4 font-medium">Generelt</h2>

		<div class="flex flex-col gap-2">
			<fieldset class="flex flex-col gap-4">
				<div class="flex gap-2">
					<FormField issues={title.issues()?.map((i) => i.message)} class="w-full">
						<Input {...title.as("text")} placeholder="Eventtitel" {disabled} />
					</FormField>
					<FormField issues={ticketUrl.issues()?.map((i) => i.message)} class="w-min min-w-72">
						<Input {...ticketUrl.as("url")} placeholder="Billet-URL" {disabled} />
					</FormField>
				</div>
			</fieldset>

			<div class="mb-4 flex gap-4">
				<FormField issues={title.issues()?.map((i) => i.message)}>
					<Select {...venueId.as("select")} {disabled}>
						{#each venues as venue}
							<option value={venue.id}>{venue.name}</option>
						{/each}
					</Select>
				</FormField>

				{#if await hasPermissions(["venues:edit"])}
					<div class="flex gap-2">
						<Button
							variant="secondary"
							type="button"
							onclick={() => getVenues(undefined).refresh()}
						>
							Refresh
						</Button>
						<Button href="/admin/venues/create" target="_blank" class="shrink-0">+ Tilføj</Button>
					</div>
				{/if}
			</div>

			{#if !disabled}
				<label for="" class="mb-4 flex items-center gap-4">
					<input {...isPublic.as("checkbox")} />
					Offentlig
				</label>
			{/if}

			<FormField issues={description.issues()?.map((i) => i.message)}>
				<Input {...description.as("text")} placeholder="Beskrivelse" {disabled} />
			</FormField>
		</div>
	</section>

	<section class="mb-16">
		<h2 class="mb-4 font-medium">Koncerter</h2>

		<ul class="flex flex-col gap-2">
			{#each rest.form.fields.concerts.value(), i}
				<li>
					<Card title="#{i + 1}">
						{#if rest.variant === "edit" && rest.form.fields.concerts[i].id.value()}
							<input
								{...rest.form.fields.concerts[i].id.as(
									"hidden",
									rest.form.fields.concerts[i].id.value()
								)}
								{disabled}
							/>
						{/if}

						<div class="flex gap-8">
							<FormField
								issues={rest.form.fields.concerts[i].artistId.issues()?.map((i) => i.message)}
								class="mb-4"
							>
								<Select
									class="w-full"
									{...rest.form.fields.concerts[i].artistId.as("select")}
									{disabled}
								>
									{#each artists as artist}
										<option selected value={artist.id}>{artist.name}</option>
									{/each}
								</Select>
							</FormField>

							<div class="flex gap-2">
								<Button
									type="button"
									variant="secondary"
									class="h-min"
									onclick={() => getArtists(undefined).refresh()}>Refresh</Button
								>
								{#if await hasPermissions(["artists:edit"])}
									<Button href="/admin/artists/create" target="_blank" class="h-min">+</Button>
								{/if}
							</div>
						</div>

						<fieldset class="flex items-center gap-2">
							<FormField
								issues={rest.form.fields.concerts[i].fromDate.issues()?.map((i) => i.message)}
							>
								<Input {...rest.form.fields.concerts[i].fromDate.as("datetime-local")} {disabled} />
							</FormField>

							<p>&gt;</p>

							<FormField
								issues={rest.form.fields.concerts[i].toDate.issues()?.map((i) => i.message)}
							>
								<Input {...rest.form.fields.concerts[i].toDate.as("datetime-local")} {disabled} />
							</FormField>
						</fieldset>
					</Card>
				</li>
			{/each}
			{#if !disabled}
				<Button type="button" variant="secondary" onclick={addConcert}>Tilføj</Button>
			{/if}
		</ul>
	</section>

	<div class="flex flex-col gap-2">
		{#if await hasPermissions(["events:edit"])}
			{#if rest.variant === "edit"}
				<Button
					type="button"
					variant="dangerous"
					class="w-full"
					onclick={() => alert("Not implemented...")}
				>
					Slet
				</Button>
			{/if}

			<Button class="w-full" type="submit">
				{#if isPublic.value() === true}
					Offentligør
				{:else}
					Upload
				{/if}
			</Button>
		{/if}
	</div>
</form>
