// frontend/src/routes/admin/events/index.tsx
import { useAuth } from '@/lib/context/auth'
import { createFileRoute } from '@tanstack/react-router'

import AdminHeader from '@/lib/components/admin-header';
import LinkButton from '@/lib/components/ui/button/link-button';
import { FaPlus } from 'react-icons/fa6';
import { useSuspenseQuery } from '@tanstack/react-query';
import { previousEventsQueryOpts, upcomingEventsQueryOpts } from '@/lib/features/event/query';
import EventList from '@/lib/features/event/components/event-list';

export const Route = createFileRoute('/admin/events/')({
  component: RouteComponent,
  loader: async ({ context: { queryClient } }) => {
    queryClient.ensureQueryData(upcomingEventsQueryOpts(false))
    queryClient.ensureQueryData(previousEventsQueryOpts)
  }
})

function RouteComponent() {
  const { hasPermissions } = useAuth()

  const { data: { records: upcomingEvents } } = useSuspenseQuery(upcomingEventsQueryOpts(false))
  const { data: { records: previousEvents } } = useSuspenseQuery(previousEventsQueryOpts)

  return (
    <>
      <AdminHeader>
        <AdminHeader.Title>Events</AdminHeader.Title>
        <AdminHeader.Description>Overblik over alle events.</AdminHeader.Description>
        <AdminHeader.Actions>
          {hasPermissions(["edit:event"]) && (
            <LinkButton
              to="/admin/events/create"
              disabled={!hasPermissions(['edit:event'])}
            >
              <FaPlus />Tilføj
            </LinkButton>
          )}
        </AdminHeader.Actions>
      </AdminHeader>

      <main className="pt-16">
        <EventList previousEvents={previousEvents} upcomingEvents={upcomingEvents} />
      </main>
    </>
  )
}

// frontend/src/routes/admin/events/+page.svelte
<script lang="ts">
	import PlusIcon from '~icons/mdi/plus';
	import Button from '$lib/components/ui/Button.svelte';

	import { hasPermissions } from '$lib/features/auth/permission';
	import EventList from './EventList.svelte';
	import DashboardLayout from '../DashboardLayout.svelte';
	import DashboardHeader from '../DashboardHeader.svelte';
	import HeaderActions from '../HeaderActions.svelte';

	let { data } = $props();
</script>

<DashboardLayout>
	<DashboardHeader title="Events" description="Overblik over alle events.">
		<HeaderActions>
			<Button
				href="/admin/events/create"
				disabled={!hasPermissions(data.member.permissions, ['edit:event'])}
			>
				<PlusIcon />Tilføj
			</Button>
		</HeaderActions>
	</DashboardHeader>

	{#if hasPermissions(data.member.permissions, ['view:event'])}
		<EventList
			previousEvents={data.previousEvents}
			upcomingEvents={data.upcomingEvents}
			memberPermissions={data.member.permissions}
		/>
	{:else}
		<span>Du har ikke tilladelse til at se denne side...</span>
	{/if}
</DashboardLayout>
