// frontend/src/routes/admin/events/EventList.svelte
<script lang="ts">
	import SearchList from '$lib/components/SearchList.svelte';
	import type { Event } from '$lib/features/event/event';
	import EventEntry from './EventEntry.svelte';

	type Props = {
		previousEvents: Event[];
		upcomingEvents: Event[];
	};

	let { previousEvents, upcomingEvents }: Props = $props();

	let search = $state('');

	let filteredEvents = $derived(
		[...previousEvents, ...upcomingEvents].filter((event) =>
			event.title.toLowerCase().includes(search.toLowerCase())
		)
	);
</script>

<SearchList bind:search>
	{#if search}
		{#each filteredEvents as event (event.id)}
			<EventEntry {event} />
		{/each}
	{:else}
		{#each upcomingEvents as event (event.id)}
			<EventEntry {event} />
		{/each}
		<details>
			<summary class="mb-4">Tidligere events ({previousEvents.length})</summary>
			{#each previousEvents as event (event.id)}
				<EventEntry {event} />
			{/each}
		</details>
	{/if}
</SearchList>

// frontend/src/lib/features/event/components/event-list.tsx
import { useMemo, useState } from 'react';

import EventEntry from './event-list-entry';
import type { Event } from '../event';
import SearchList from '@/lib/components/search-list';

type Props = {
	previousEvents: Event[];
	upcomingEvents: Event[];
};

const filterEventsBySearch = (events: Event[], query: string) => query
	? events.filter(e => e.title.toLowerCase().includes(query.toLowerCase()))
	: events

const EventList = ({ previousEvents, upcomingEvents }: Props) => {
	let [search, setSearch] = useState("");

	let filteredEvents = useMemo(() =>
		filterEventsBySearch([...previousEvents, ...upcomingEvents], search),
		[search, previousEvents, upcomingEvents]
	)

	return (
		<SearchList search={search} onChange={(newSearch) => setSearch(newSearch)}>
			{search
				? filteredEvents.map(event => <EventEntry key={event.id} event={event} />)
				: upcomingEvents.map(event => <EventEntry key={event.id} event={event} />)}

			<details>
				<summary className="mb-4">Tidligere events ({previousEvents.length})</summary>
				{previousEvents.map(event => <EventEntry key={event.id} event={event} />)}
			</details>
		</SearchList >
	)
}

export default EventList
