// frontend/src/routes/admin/artists/create.tsx
import { APIError } from '@/lib/api'
import ArtistForm from '@/lib/components/artist-form'
import { useToast } from '@/lib/context/toast'
import { createArtist, type createArtistForm } from '@/lib/features/artist'
import { useGenres } from '@/lib/features/hook'
import { useQueryClient } from '@tanstack/react-query'
import { createFileRoute, useNavigate } from '@tanstack/react-router'
import type { z } from 'zod'

export const Route = createFileRoute('/admin/artists/create')({
  component: RouteComponent,
})

function RouteComponent() {
  const { addToast } = useToast()
  const navigate = useNavigate()
  const queryClient = useQueryClient()

  const genreQuery = useGenres()

  const genres = genreQuery.data?.records || []

  const onSubmit = async (form: z.infer<typeof createArtistForm>) => {
    try {
      await createArtist(form)
      addToast("Kunstner lavet")
      await queryClient.invalidateQueries({ queryKey: ["artists"] })
      navigate({ to: "/admin/artists" })
    } catch (e) {
      if (e instanceof APIError) {
        addToast("Kunne ikke lave kunstner", e.message, "error")
        throw e
      }

      addToast("Kunne ikke lave kunstner", "Noget gik galt...", "error")
      throw e
    }
  }

  return (
    <ArtistForm genres={genres} onSubmit={onSubmit} />
  )
}

// frontend/src/routes/admin/venues/create/+page.svelte
<script lang="ts">
	import { ZodError, type z } from 'zod';
	import VenueForm from '../VenueForm.svelte';
	import { createVenue, createVenueForm } from '$lib/features/venue/venue';
	import { toaster } from '$lib/toaster.svelte';
	import { goto, invalidateAll } from '$app/navigation';

	let errors = $state<z.inferFlattenedErrors<typeof createVenueForm>>();

	const handleSubmit = async (form: z.infer<typeof createVenueForm>) => {
		try {
			await createVenue(fetch, form);
			toaster.addToast('Venue skabt.');
			await invalidateAll();
			await goto('/admin/venues');
		} catch (e) {
			if (e instanceof ZodError) {
				errors = e.flatten();
				return;
			}
			toaster.addToast('Kunne ikke lave venue', 'Noget gik galt...', 'error');
		}
	};
</script>

<main class="flex items-center justify-center px-8 py-16 md:px-16">
	<VenueForm {errors} onSubmit={handleSubmit} />
</main>
