// frontend/src/lib/components/ui/selector.tsx
import { cn } from "@/lib/clsx";
import { forwardRef, type SelectHTMLAttributes } from "react";

type Props = SelectHTMLAttributes<HTMLSelectElement> & {
	placeholder?: string;
};

const Selector = forwardRef<HTMLSelectElement, Props>(({ placeholder = "Vælg...", defaultValue, children, className, ...rest }, ref) => (
	<select
		ref={ref}
		{...rest}
		defaultValue={defaultValue || "placeholder"}
		className={cn('disabled:text-text/50 rounded-sm border border-zinc-900 bg-zinc-950', className)}
	>
		<option value="placeholder" disabled>{placeholder}</option>
		{children}
	</select>
))

export default Selector

// frontend_bak/src/lib/components/Selector.svelte
<script lang="ts">
	import { cn } from '$lib/clsx';
	import type { HTMLSelectAttributes } from 'svelte/elements';

	type Entry = {
		name: string;
		value: string;
	};

	type Props = HTMLSelectAttributes & {
		entries: Entry[];
	};

	let { entries, children, ...rest }: Props = $props();
</script>

<select {...rest} class={cn('rounded-sm border border-zinc-900 bg-zinc-950', rest.class)}>
	{#each entries as entry (entry.value)}
		<option value={entry.value}>{entry.name}</option>
	{/each}
</select>
