// frontend/src/lib/components/Card.svelte
<script lang="ts">
	import type { HTMLAttributes } from "svelte/elements";

	type Props = Omit<HTMLAttributes<HTMLDivElement>, "title"> & {
		title: string;
		description?: string;
		variant?: "darker" | "lighter";
	};

	let { title, description, variant = "darker", children, ...rest }: Props = $props();
</script>

<div
	class={[
		"rounded-xl border px-8 py-12",
		variant === "darker" && "border-zinc-900 bg-zinc-950",
		variant === "lighter" && "border-zinc-800 bg-zinc-900",
		,
		rest.class
	]}
>
	<div class="mb-8">
		<h1 class="font-heading mb-4 text-4xl font-black text-text-light">{title}</h1>
		{#if description}
			<p class="leading-relaxed">{description}</p>
		{/if}
	</div>

	{@render children?.()}
</div>

// frontend/src/lib/components/ui/card.tsx
import { cn } from "@/lib/clsx";
import type { HTMLAttributes } from "react";

const Card = ({
  children,
  className,
  ...rest
}: HTMLAttributes<HTMLDivElement>) => {
  return (
    <div
      {...rest}
      className={cn("rounded-xl border border-zinc-800 bg-zinc-950", className)}
    >
      {children}
    </div>
  );
};

const Header = ({
  children,
  className,
  ...rest
}: HTMLAttributes<HTMLDivElement>) => {
  return (
    <div {...rest} className={cn("flex flex-col gap-2 p-8 pt-12", className)}>
      {children}
    </div>
  );
};

const Content = ({
  children,
  className,
  ...rest
}: HTMLAttributes<HTMLDivElement>) => {
  return (
    <div {...rest} className={cn("flex flex-col p-6", className)}>
      {children}
    </div>
  );
};

const Title = ({
  children,
  className,
  ...rest
}: HTMLAttributes<HTMLHeadingElement>) => {
  return (
    <h1
      {...rest}
      className={cn(
        "mb-4 font-heading text-3xl font-bold text-text-light",
        className,
      )}
    >
      {children}
    </h1>
  );
};

const Description = ({
  children,
  ...rest
}: HTMLAttributes<HTMLParagraphElement>) => {
  return (
    <p {...rest} className="text-text/50">
      {children}
    </p>
  );
};

const Footer = ({ children, ...rest }: HTMLAttributes<HTMLDivElement>) => {
  return (
    <div {...rest} className="p-6 pb-12">
      {children}
    </div>
  );
};

Card.Header = Header;
Card.Content = Content;

Card.Title = Title;
Card.Description = Description;
Card.Footer = Footer;

export default Card;
