// frontend/src/lib/components/form-field.tsx
import { cn } from "@/lib/clsx";
import type { HTMLAttributes } from "react";
import type { FieldError, FieldErrorsImpl, Merge } from "react-hook-form";

type Error = Merge<FieldError, (Merge<FieldError, FieldErrorsImpl<{
	value: string;
}>> | undefined)[]> | FieldError | undefined


type Props = HTMLAttributes<HTMLDivElement> & {
	error?: Error;
}

const FormField = ({ error, children, className }: Props) => (
	<div className={cn("flex flex-col gap-2", className)}>
		<div className="flex gap-4 w-full">
			{children}
		</div>

		{error && (
			<span className={cn("text-sm hidden text-red-500", { "block": error })}>
				{error?.message}
			</span>
		)}
	</div>
)

export default FormField

// frontend/src/lib/components/ui/FormField.svelte
<script lang="ts">
	import { cn } from '$lib/clsx';
	import type { HTMLAttributes } from 'svelte/elements';

	type Props = HTMLAttributes<HTMLDivElement> & {
		errors?: string[] | undefined;
		maxErrorCount?: number;
	};

	let { children, maxErrorCount = 5, errors }: Props = $props();
</script>

<div class="flex w-full flex-col gap-2">
	{@render children?.()}

	<ul
		class={cn('hidden min-h-5 list-inside text-sm text-red-500', {
			block: errors && errors.length > 0,
			'list-disc': errors && errors.length > 1
		})}
	>
		{#each errors?.slice(0, maxErrorCount) || [] as error}
			<li>{error}</li>
		{/each}
	</ul>
</div>
