// frontend/src/lib/components/ui/Input.svelte
<script lang="ts">
	import type { HTMLInputAttributes } from 'svelte/elements';

	type Props = HTMLInputAttributes;

	let { value = $bindable(''), ...rest }: Props = $props();
</script>

<input
	{...rest}
	bind:value
	class="bg-background disabled:text-text/50 w-full rounded-sm border border-zinc-900 px-3 py-2"
/>

// frontend/src/lib/components/ui/input.tsx
import { cn } from '@/lib/clsx';
import { forwardRef, type InputHTMLAttributes } from 'react';

const Input = forwardRef<HTMLInputElement, InputHTMLAttributes<HTMLInputElement>>(({ className, ...rest }, ref) => {
	return (
		<input
			ref={ref}
			{...rest}
			className={cn("bg-background disabled:text-text/50 w-full rounded-sm border border-zinc-900 px-4 py-2", className)}
		/>
	)
})

export default Input
