// frontend/src/lib/components/ui/input/input.tsx
import { cn } from "@/lib/clsx";
import { forwardRef, type InputHTMLAttributes } from "react";

type Props = InputHTMLAttributes<HTMLInputElement>

const Input = forwardRef<HTMLInputElement, Props>(({ className, ...rest }, ref) => (
	<input ref={ref} {...rest} className={cn("w-full px-4 py-2 border bg-background border-zinc-900 rounded-sm focus:outline-none", className)} />
))

export default Input

// frontend/src/lib/components/ui/Input.svelte
<script lang="ts">
	import type { HTMLInputAttributes } from 'svelte/elements';

	type Props = HTMLInputAttributes;

	let { value = $bindable(''), ...rest }: Props = $props();
</script>

<input
	{...rest}
	bind:value
	class="bg-background disabled:text-text/50 w-full rounded-sm border border-zinc-900 px-3 py-2"
/>
