// frontend/src/routes/admin/events/EventForm.svelte
<script lang="ts">
	import { SvelteMap } from 'svelte/reactivity';

	import type { z } from 'zod';
	import { addMinutes, roundToNearestHours } from 'date-fns';

	import type { Artist } from '$lib/features/artist/artist';
	import type { Venue } from '$lib/features/venue/venue';

	import type { concertForm } from '$lib/features/concert/concert';
	import type { createEventForm, editEventForm, Event } from '$lib/features/event/event';

	import ConcertsList from './ConcertsList.svelte';
	import PublishIcon from '~icons/mdi/upload';
	import RefreshIcon from '~icons/mdi/refresh';
	import AddIcon from '~icons/mdi/add';

	import Input from '$lib/components/ui/Input.svelte';
	import Selector from '$lib/components/ui/Selector.svelte';
	import ImagePreview from '$lib/components/ImagePreview.svelte';
	import TipTapEditor from '$lib/components/tiptap/TipTapEditor.svelte';
	import Button from '$lib/components/ui/Button.svelte';
	import Spinner from '$lib/components/Spinner.svelte';
	import FormField from '$lib/components/ui/FormField.svelte';
	import { invalidateAll } from '$app/navigation';

	type Props = {
		venues: Venue[];
		artists: Artist[];

		event?: Event;
		errors:
			| z.typeToFlattenedError<z.infer<typeof createEventForm> | z.infer<typeof editEventForm>>
			| undefined;

		loading: boolean;

		onSubmit: (form: z.infer<typeof createEventForm> | z.infer<typeof editEventForm>) => void;
	};

	let { event, venues, artists, errors, loading, onSubmit }: Props = $props();

	const form = $state<z.infer<typeof createEventForm> | z.infer<typeof editEventForm>>(
		event
			? {
					...event,
					venueId: event.venue.id,
					image: null,
					concerts: event.concerts.map(({ artist, from, to }) => ({
						artistID: artist.id,
						from,
						to
					}))
				}
			: {
					title: '',
					description: '',
					concerts: [],
					image: null,
					venueId: 1,
					ticketUrl: ''
				}
	);

	const imageUrl = $derived(form.image ? URL.createObjectURL(form.image) : event?.imageUrl);

	let concerts = $state(
		new SvelteMap<string, z.infer<typeof concertForm>>(
			form.concerts.map((concert) => [crypto.randomUUID(), concert])
		)
	);

	const deleteConcert = (id: string) => {
		concerts.delete(id);
	};

	const addConcert = () => {
		const lastConcert = Array.from(concerts).at(-1)?.[1];

		const from = lastConcert?.to || roundToNearestHours(new Date());
		const to = addMinutes(from, 30);

		const id = crypto.randomUUID();

		concerts.set(id, { from, to, artistID: 1 });
	};

	const handleSubmit = (e: SubmitEvent) => {
		e.preventDefault();

		onSubmit({
			...form,
			concerts: Array.from(concerts.entries()).map(([_, concert]) => concert)
		});
	};
</script>

<form onsubmit={handleSubmit} class="space-y-16">
	<!-- COVER IMAGE -->
	<section>
		<h2 class="mb-8 text-2xl font-semibold">Coverbillede</h2>
		<FormField errors={errors?.fieldErrors.image}>
			<ImagePreview
				accept="image/jpeg,image/png"
				src={imageUrl}
				onChange={(file) => (form.image = file)}
			/>
		</FormField>
	</section>

	<!-- GENERAL -->
	<section>
		<h2 class="mb-8 text-2xl font-semibold">Generelt</h2>

		<div class="space-y-4">
			<FormField errors={errors?.fieldErrors.title}>
				<Input placeholder="Eventtitel" bind:value={form.title} class="flex-1" />
			</FormField>

			<div class="flex w-full gap-4">
				<FormField errors={errors?.fieldErrors.ticketUrl}>
					<Input placeholder="Billet-URL" class="flex-1" bind:value={form.ticketUrl} />
				</FormField>

				<FormField errors={errors?.fieldErrors.venueId}>
					<div class="flex gap-2">
						<Selector
							class="w-full"
							placeholder="Vælg venue..."
							bind:value={() => form.venueId.toString(), (v) => (form.venueId = parseInt(v))}
							entries={venues.map((venue) => ({ name: venue.name, value: venue.id.toString() }))}
						/>
						<Button
							title="Lav nyt venue"
							class="aspect-square h-full"
							target="__blank"
							variant="primary"
							href="/admin/venues/create"><AddIcon /></Button
						>
						<Button
							title="Opdatér venueliste"
							variant="secondary"
							class="aspect-square h-full"
							onclick={async () => await invalidateAll()}><RefreshIcon /></Button
						>
					</div>
				</FormField>
			</div>
			<!-- EVENT DESCRIPTION -->
			<FormField errors={errors?.fieldErrors.description}>
				<TipTapEditor bind:value={form.description} />
			</FormField>
		</div>
	</section>

	<!-- CONCERTS -->
	<section>
		<h2 class="mb-4 text-2xl font-semibold">Koncerter</h2>
		<FormField errors={errors?.fieldErrors.concerts}>
			<ConcertsList {concerts} {artists} onAdd={addConcert} onDelete={deleteConcert} />
		</FormField>
	</section>

	<Button type="submit" class="w-full md:max-w-64">
		{#if loading}
			<Spinner />
			Offentligører...
		{:else}
			<PublishIcon />
			Offentliggør
		{/if}
	</Button>
</form>

// frontend/src/lib/components/event-form/event-form.tsx
import { FormProvider, useFieldArray, useForm, type UseFieldArrayReturn, type UseFormReturn } from "react-hook-form"
import { zodResolver } from "@hookform/resolvers/zod"
import { FaArrowsRotate, FaPlus, FaUpload } from "react-icons/fa6"
import { addMinutes, roundToNearestHours } from "date-fns"
import ConcertList from "./concert-list"
import { z } from "zod"
import { createEventForm, editEventForm, type Event } from "@/lib/features/event"
import type { Venue } from "@/lib/features/venue"
import FormField from "../form-field"
import ImagePreview from "../image-preview"
import Input from "../ui/input"
import Selector from "../ui/selector"
import Button from "../ui/button/button"
import LinkButton from "../ui/button/link-button"
import type { Artist } from "@/lib/features/artist"
import { createContext, useContext } from "react"
import Tiptap from "../tiptap/tiptap"

// We must include the fieldArray as part of the context, to not create another
// instance in children.
//
// This also means, that we are NOT to use the react-hook-form useFormContext,
// but rather the extended useEventFormContext!
type EventFormContext =
	UseFieldArrayReturn<EventForm> &
	UseFormReturn<EventForm> & {
		event?: Event;
		venues: Venue[]
		artists: Artist[]

		onAddConcert: () => void;
		onDeleteConcert: (index: number) => void
		disabled: boolean;
	}

const EventFormContext = createContext<EventFormContext | undefined>(undefined)

export const useEventFormContext = () => {
	const eventFormContext = useContext(EventFormContext)

	if (!eventFormContext) throw new Error("No provider for EventFormContext")

	return eventFormContext
}


const eventFormSchema = z.union([createEventForm, editEventForm])
type EventForm = z.infer<typeof eventFormSchema>

type Props = {
	event?: Event;
	venues: Venue[]
	artists: Artist[]
	disabled?: boolean;

	onSubmit: (form: EventForm) => void;
}

const EventForm = ({ event, venues, artists, disabled = false, onSubmit }: Props) => {
	const methods = useForm<EventForm>({
		defaultValues: {
			...event,
			venueId: event?.venue.id,
			concerts: event?.concerts.map(c => ({
				from: c.from,
				to: c.to,
				artistID: c.artist.id,
			}))
		},
		resolver: zodResolver(eventFormSchema),
	})

	const { control, formState: { defaultValues, errors }, setValue, getValues, handleSubmit } = methods;

	const fieldArrayMethods = useFieldArray({ control, name: "concerts" })
	const { fields, remove, append } = fieldArrayMethods


	const onAddConcert = () => {
		const prevEnd = fields.length > 0
			? getValues(`concerts.${fields.length - 1}.to`)
			: undefined

		const from = prevEnd ? addMinutes(prevEnd, 15) : roundToNearestHours(new Date())
		const to = addMinutes(from, 30)
		append({ artistID: 1, from, to })
	}

	const onDeleteConcert = (idx: number) => {
		remove(idx)
	}

	return (
		<FormProvider {...methods}>
			<EventFormContext.Provider value={{ ...methods, ...fieldArrayMethods, artists, venues, event, disabled, onAddConcert, onDeleteConcert }}>
				<form onSubmit={handleSubmit(onSubmit)} className="flex flex-col gap-16">
					<FormField error={errors.image}>
						<ImagePreview src={event?.imageUrl} accept="image/jpeg,image/png" onChange={file => setValue("image", file)} />
					</FormField>

					<GeneralSection />

					<FormField error={errors.description}>
						<Tiptap content={defaultValues?.description} onChange={(html) => setValue("description", html)} />
					</FormField>

					<ConcertsSection />

					<Button className="w-full md:w-fit" type="submit"><FaUpload />Offentliggør</Button>
				</form>
			</EventFormContext.Provider>
		</FormProvider>
	)
}

const GeneralSection = () => {
	const { register, formState: { errors } } = useEventFormContext()

	return (
		<section>

			<h1 className="text-2xl font-heading font-bold mb-4">Generelt</h1>
			<div className="flex flex-col gap-4">
				<FormField error={errors.title}>
					<Input {...register("title")} placeholder="Eventtitel" />
				</FormField>

				<div className="flex gap-4">
					<FormField error={errors.ticketUrl}>
						<Input {...register("ticketUrl")} placeholder="Billet-URL" className="w-full" />
					</FormField>

					<VenueSelector />
				</div>
			</div>
		</section>
	)
}

const ConcertsSection = () => {
	const { fields } = useEventFormContext()
	return (
		<section>
			<h1 className="text-2xl font-bold font-heading mb-4">Koncerter</h1>
			<ConcertList>
				{fields.map((field, index) => (
					<ConcertList.Entry key={field.id} index={index} />
				))}
			</ConcertList>
		</section>
	)
}

const VenueSelector = () => {
	const { venues, disabled } = useEventFormContext()

	const {
		setValue,
		getValues,
		formState: { errors },
	} = useEventFormContext()

	return (
		<FormField error={errors.venueId}>
			<Selector
				onChange={e => setValue("venueId", parseInt(e.target.value))}
				defaultValue={venues.find(v => v.id === getValues("venueId"))?.id}
				placeholder="Vælg venue..."
				className="w-full"
			>
				{venues.map(v => (
					<option key={v.id} value={v.id}>{v.name}</option>
				))}
			</Selector>

			{!disabled && (
				<div className="flex gap-2">
					<Button variant="ghost" className="aspect-square h-full">
						<FaArrowsRotate />
					</Button>
					<LinkButton to="/admin/venues/create" className="aspect-square h-full">
						<FaPlus />
					</LinkButton>
				</div>
			)}
		</FormField>
	)
}

export default EventForm
