// frontend/src/routes/admin/events/edit/EventForm.svelte
<script lang="ts">
	import { z, ZodError } from 'zod';
	import { addMinutes, roundToNearestHours } from 'date-fns';

	import type { Artist } from '$lib/artist';
	import type { Venue } from '$lib/venue';
	import { eventForm, type Event } from '$lib/event';
	import { concertForm } from '$lib/concert';

	import Button from '$lib/components/ui/Button.svelte';
	import Input from '$lib/components/ui/Input.svelte';
	import FieldError from '$lib/components/ui/FieldError.svelte';
	import Selector from '$lib/components/ui/Selector.svelte';
	import ImagePreview from '$lib/components/ui/ImagePreview.svelte';
	import CreateConcertCard from './CreateConcertCard.svelte';

	import PlusIcon from '~icons/mdi/plus';
	import { goto } from '$app/navigation';

	type Props = {
		event: Event | null;
		artists: Artist[];
		venues: Venue[];

		onSubmit: (e: z.infer<typeof eventForm>) => void;
	};

	const { event, artists, venues, onSubmit }: Props = $props();

	const concertWithID = concertForm.extend({ id: z.string().uuid() });

	const extendedForm = eventForm.extend({
		concerts: concertWithID.array()
	});

	let form = $state<z.infer<typeof extendedForm>>({
		title: event?.title || '',
		description: event?.description || '',
		ticketUrl: event?.ticketUrl || '',
		venueId: event?.venue.id || 1,
		image: null,
		concerts:
			event?.concerts.map((c) => ({
				id: crypto.randomUUID().toString(),
				artistID: c.artist.id,
				from: c.from,
				to: c.to
			})) || []
	});

	let formError = $state<ZodError>();
	let imageUrl = $derived(form.image ? URL.createObjectURL(form.image) : event?.imageUrl || '');

	const deleteConcert = (id: string) => {
		form.concerts = form.concerts.filter((c) => c.id !== id);
	};

	const addConcert = () => {
		const from = form.concerts.length > 0 ? form.concerts[0]?.to : roundToNearestHours(new Date());
		const to = addMinutes(from, 30);

		form.concerts = [
			...form.concerts,
			{ id: crypto.randomUUID().toString(), artistID: 1, from, to }
		];
	};

	const submit = (e: SubmitEvent & { currentTarget: EventTarget & HTMLFormElement }) => {
		e.preventDefault();

		const { error, data, success } = eventForm.safeParse(form);
		if (!success) {
			formError = error;
			return;
		}

		onSubmit(data);
	};
</script>

<form class="space-y-8" onsubmit={submit}>
	<h1 class="mb-8 text-2xl font-bold">Lav event</h1>
	<div>
		<ImagePreview src={imageUrl || ''} onChange={(file) => (form.image = file)} />
		<FieldError errors={formError?.flatten().fieldErrors['imageUrl']} />
	</div>
	{@render generalSection()}
	{@render concertsSection()}
	<div class="flex gap-4">
		<Button variant="secondary">Preview</Button>
		<Button type="submit">Offentligør</Button>
	</div>
</form>

{#snippet generalSection()}
	<div>
		<h1 class="mb-4 text-2xl font-bold">Generelt</h1>
		<FieldError errors={formError?.flatten().fieldErrors['image']} />
		<div class="space-y-8">
			<div class="flex gap-4 *:flex-1">
				<Input
					errors={formError?.flatten().fieldErrors['title']}
					label="Titel"
					type="text"
					name="title"
					bind:value={form.title}
				/>
				<div class="flex flex-col">
					<div class="flex gap-2">
						<Selector
							class="w-full"
							onchange={(e) => (form.venueId = parseInt(e.currentTarget.value))}
							value={form.venueId.toString()}
							entries={venues.map((v) => ({
								name: `${v.name}, ${v.city}`,
								value: v.id.toString()
							}))}
						/>
						<Button type="submit" onclick={() => goto('/admin/venues')}><PlusIcon />Tilføj</Button>
					</div>
					<FieldError errors={formError?.flatten().fieldErrors['venueId']} />
				</div>
			</div>
			<Input
				errors={formError?.flatten().fieldErrors['ticketUrl']}
				label="Billet-URL"
				bind:value={form.ticketUrl}
			/>
			<Input
				errors={formError?.flatten().fieldErrors['description']}
				label="Beskrivelse"
				bind:value={form.description}
			/>
		</div>
	</div>
{/snippet}

{#snippet concertsSection()}
	<div class="space-y-6">
		<h1 class="text-2xl font-bold">Koncerter</h1>
		<div class="space-y-4">
			{#each form.concerts || [] as concert, i (concert.id)}
				<CreateConcertCard
					bind:concert={form.concerts[i]}
					{artists}
					idx={i + 1}
					onDelete={() => deleteConcert(concert.id)}
				/>
			{/each}
		</div>
		<Button onclick={addConcert} variant="ghost">+ Tilføj koncert</Button>
		<FieldError errors={formError?.flatten().fieldErrors['concerts']} />
	</div>
{/snippet}

// frontend/src/lib/components/event-form/event-form.tsx
import { FormProvider, useFieldArray, useForm, type UseFieldArrayReturn, type UseFormReturn } from "react-hook-form"
import { zodResolver } from "@hookform/resolvers/zod"
import { FaArrowsRotate, FaPlus, FaUpload } from "react-icons/fa6"
import { addMinutes, roundToNearestHours } from "date-fns"
import ConcertList from "./concert-list"
import { z } from "zod"
import { createEventForm, editEventForm, type Event } from "@/lib/features/event"
import type { Venue } from "@/lib/features/venue"
import FormField from "../form-field"
import ImagePreview from "../image-preview"
import Input from "../ui/input"
import Selector from "../ui/selector"
import Button from "../ui/button/button"
import LinkButton from "../ui/button/link-button"
import type { Artist } from "@/lib/features/artist"
import { createContext, useContext } from "react"
import Tiptap from "../tiptap/tiptap"

// We must include the fieldArray as part of the context, to not create another
// instance in children.
//
// This also means, that we are NOT to use the react-hook-form useFormContext,
// but rather the extended useEventFormContext!
type EventFormContext =
	UseFieldArrayReturn<EventForm> &
	UseFormReturn<EventForm> & {
		event?: Event;
		venues: Venue[]
		artists: Artist[]

		onAddConcert: () => void;
		onDeleteConcert: (index: number) => void
		disabled: boolean;
	}

const EventFormContext = createContext<EventFormContext | undefined>(undefined)

export const useEventFormContext = () => {
	const eventFormContext = useContext(EventFormContext)

	if (!eventFormContext) throw new Error("No provider for EventFormContext")

	return eventFormContext
}


const eventFormSchema = z.union([createEventForm, editEventForm])
type EventForm = z.infer<typeof eventFormSchema>

type Props = {
	event?: Event;
	venues: Venue[]
	artists: Artist[]
	disabled?: boolean;

	onSubmit: (form: EventForm) => void;
}

const EventForm = ({ event, venues, artists, disabled = false, onSubmit }: Props) => {
	const methods = useForm<EventForm>({
		defaultValues: {
			...event,
			venueId: event?.venue.id,
			concerts: event?.concerts.map(c => ({
				from: c.from,
				to: c.to,
				artistID: c.artist.id,
			}))
		},
		resolver: zodResolver(eventFormSchema),
	})

	const { control, formState: { defaultValues, errors }, setValue, getValues, handleSubmit } = methods;

	const fieldArrayMethods = useFieldArray({ control, name: "concerts" })
	const { fields, remove, append } = fieldArrayMethods


	const onAddConcert = () => {
		const prevEnd = fields.length > 0
			? getValues(`concerts.${fields.length - 1}.to`)
			: undefined

		const from = prevEnd ? addMinutes(prevEnd, 15) : roundToNearestHours(new Date())
		const to = addMinutes(from, 30)
		append({ artistID: 1, from, to })
	}

	const onDeleteConcert = (idx: number) => {
		remove(idx)
	}

	return (
		<FormProvider {...methods}>
			<EventFormContext.Provider value={{ ...methods, ...fieldArrayMethods, artists, venues, event, disabled, onAddConcert, onDeleteConcert }}>
				<form onSubmit={handleSubmit(onSubmit)} className="flex flex-col gap-16">
					<FormField error={errors.image}>
						<ImagePreview src={event?.imageUrl} accept="image/jpeg,image/png" onChange={file => setValue("image", file)} />
					</FormField>

					<GeneralSection />

					<FormField error={errors.description}>
						<Tiptap content={defaultValues?.description} onChange={(html) => setValue("description", html)} />
					</FormField>

					<ConcertsSection />

					<Button className="w-full md:w-fit" type="submit"><FaUpload />Offentliggør</Button>
				</form>
			</EventFormContext.Provider>
		</FormProvider>
	)
}

const GeneralSection = () => {
	const { register, formState: { errors } } = useEventFormContext()

	return (
		<section>

			<h1 className="text-2xl font-heading font-bold mb-4">Generelt</h1>
			<div className="flex flex-col gap-4">
				<FormField error={errors.title}>
					<Input {...register("title")} placeholder="Eventtitel" />
				</FormField>

				<div className="flex gap-4">
					<FormField error={errors.ticketUrl}>
						<Input {...register("ticketUrl")} placeholder="Billet-URL" className="w-full" />
					</FormField>

					<VenueSelector />
				</div>
			</div>
		</section>
	)
}

const ConcertsSection = () => {
	const { fields } = useEventFormContext()
	return (
		<section>
			<h1 className="text-2xl font-bold font-heading mb-4">Koncerter</h1>
			<ConcertList>
				{fields.map((field, index) => (
					<ConcertList.Entry key={field.id} index={index} />
				))}
			</ConcertList>
		</section>
	)
}

const VenueSelector = () => {
	const { venues, disabled } = useEventFormContext()

	const {
		setValue,
		getValues,
		formState: { errors },
	} = useEventFormContext()

	return (
		<FormField error={errors.venueId}>
			<Selector
				onChange={e => setValue("venueId", parseInt(e.target.value))}
				defaultValue={venues.find(v => v.id === getValues("venueId"))?.id}
				placeholder="Vælg venue..."
				className="w-full"
			>
				{venues.map(v => (
					<option key={v.id} value={v.id}>{v.name}</option>
				))}
			</Selector>

			{!disabled && (
				<div className="flex gap-2">
					<Button variant="ghost" className="aspect-square h-full">
						<FaArrowsRotate />
					</Button>
					<LinkButton to="/admin/venues/create" className="aspect-square h-full">
						<FaPlus />
					</LinkButton>
				</div>
			)}
		</FormField>
	)
}

export default EventForm
