// frontend/src/lib/features/artist/components/artist-form.tsx
import { createContext, useContext, useState } from "react"
import { z } from "zod"

import { FormProvider, useFieldArray, useForm, type UseFieldArrayReturn, type UseFormReturn } from "react-hook-form"
import { zodResolver } from "@hookform/resolvers/zod"

import { FaPlus, FaTrash, FaUpload, FaPen } from "react-icons/fa"
import { artistForm, createArtist, socialUrlToIcon, updateArtist, type Artist, type ArtistFormValues } from "../artist"
import type { Genre } from "../genre"
import FormField from "@/lib/components/form-field"
import ImagePreview from "@/lib/components/image-preview"
import Button from "@/lib/components/ui/button/button"
import Input from "@/lib/components/ui/input"
import Tiptap from "@/lib/components/tiptap/tiptap"
import { trackIdFromUrl } from "@/lib/spotify"
import SpotifyPreview from "@/lib/components/spotify-preview"
import type { Entry } from "@/lib/components/ui/picker"
import PillList from "@/lib/components/pill-list"
import Picker from "@/lib/components/ui/picker"
import { createSubmitHandler } from "@/lib/api"
import { useQueryClient } from "@tanstack/react-query"

const internalSocialSchema = z.object({ value: z.string().url() })

const internalArtistFormSchema = artistForm
	.omit({ socials: true })
	.extend({ socials: internalSocialSchema.array() })

type InternalArtistForm = z.infer<typeof internalArtistFormSchema>

type ArtistFormContext =
	UseFormReturn<InternalArtistForm> &
	UseFieldArrayReturn<InternalArtistForm> & {
		artist: Artist | undefined;
		genres: Genre[]
	}

const ArtistFormContext = createContext<ArtistFormContext | undefined>(undefined)

export const useArtistFormContext = () => {
	const ctx = useContext(ArtistFormContext)
	if (!ctx) throw new Error("No Provider for ArtistFormContext")
	return ctx
}

type Props = {
	artist?: Artist;
	genres: Genre[]
}

const ArtistForm = ({ artist, genres }: Props) => {
	const methods = useForm<InternalArtistForm>({
		defaultValues: {
			...artist,
			genreIds: artist?.genres.map(genre => genre.id) || [],
			socials: artist?.socials.map(s => ({ value: s }))
		},
		resolver: zodResolver(internalArtistFormSchema),
	})

	const { control, formState: { errors }, handleSubmit, setValue } = methods
	const fieldArrayMethods = useFieldArray({ control, name: "socials" })

	const queryClient = useQueryClient()

	const onSubmit = createSubmitHandler({
		navigateTo: "/admin/artists",
		successMessage: artist ? "Kunstner redigeret" : "Kunstner skabt",
		errorMessage: artist ? "Kunne ikke redigere kunstner" : "Kunne ikke skabe kunstner",
		action: async (form: InternalArtistForm) => {
			const socials: string[] = form.socials.map(({ value }) => value)
			const output: ArtistFormValues = { ...form, socials }

			const { data, success, error } = artistForm.safeParse(output)
			if (!success) {
				console.error(error)
				throw error
			}

			artist
				? await updateArtist(artist.id, data)
				: await createArtist(data)

			await queryClient.invalidateQueries({ queryKey: ["artists"] })
		},
	})

	return (
		<ArtistFormContext.Provider value={{ ...methods, ...fieldArrayMethods, artist, genres }}>
			<FormProvider {...methods}>
				<form className="flex flex-col gap-16" onSubmit={handleSubmit(onSubmit)}>
					<FormField error={errors.image}>
						<ImagePreview
							src={artist?.imageUrl}
							accept="image/jpeg,image/png"
							onChange={(file) => setValue("image", file)}
						/>
					</FormField>

					<GeneralSection />
					<SpotifySection />
					<GenreSection />
					<SocialsSection />

					<Button type="submit" className="w-full md:w-fit"><FaUpload />Offentligør</Button>
				</form>
			</FormProvider>
		</ArtistFormContext.Provider>
	)
}

const GeneralSection = () => {
	const { register, setValue, formState: { errors, defaultValues } } = useArtistFormContext()

	return (
		<section >
			<h1 className="font-heading text-2xl font-bold mb-4">Generelt</h1>
			<div className="flex flex-col gap-4">
				<FormField error={errors.name}>
					<Input placeholder="Kunstnernavn" {...register("name")} />
				</FormField>

				<FormField error={errors.description}>
					<Tiptap
						content={defaultValues?.description}
						onChange={(html) => setValue("description", html)}
					/>
				</FormField>
			</div>
		</section>
	)

}

const SpotifySection = () => {
	const { register, watch } = useArtistFormContext()

	const trackId = trackIdFromUrl(watch("previewUrl"))

	return (
		<section>
			<h1 className="text-2xl font-bold font-heading mb-8">Spotify Preview</h1>
			<div className="flex flex-col gap-4">
				<Input placeholder="Spotify Preview-URL..." {...register("previewUrl")} />
				{trackId && <SpotifyPreview trackId={trackId} />}
			</div>
		</section>
	)
}

const GenreSection = () => {
	const { genres, setValue, formState: { errors }, watch } = useArtistFormContext()
	const [showPicker, setShowPicker] = useState(false)

	const entries: Entry[] = genres.map(genre => ({
		id: genre.id.toString(),
		value: genre.id.toString(),
		name: genre.name,
	}))

	const selected = entries.filter(entry =>
		watch("genreIds").includes(parseInt(entry.value))
	)

	return (
		<section>
			<h1 className="font-bold font-heading mb-8 text-2xl">Genrer</h1>

			<FormField error={errors.genreIds}>
				<PillList entries={selected.map(entry => entry.name)}>
					<Button variant="ghost" onClick={() => setShowPicker(true)} className="h-10 rounded-full px-4" ><FaPen />Vælg</Button>
				</PillList>
			</FormField>

			<Picker
				title="Vælg genrer..."
				description="Her kan du vælge de genrer, som kunstneren associeres med."
				entries={entries}
				selected={selected}
				show={showPicker}
				onClose={() => setShowPicker(false)}
				onChange={(selectedEntries) =>
					setValue("genreIds", selectedEntries.map(entry => parseInt(entry.value)))
				}
			/>
		</section>
	)
}

const SocialsSection = () => {
	const { fields, formState: { errors }, append } = useArtistFormContext()

	const [input, setInput] = useState("")

	return (
		<section>
			<h1 className="font-heading font-bold text-2xl mb-4">Sociale medier</h1>

			<div className="w-full flex gap-4 mb-8">
				<Input placeholder="URL..." value={input} onChange={e => setInput(e.target.value)} />
				<Button variant="secondary" onClick={() => append({ value: input })}><FaPlus /> Tilføj</Button>
			</div>

			<div className="flex flex-col gap-2">
				{fields.map((field, index) => (
					<FormField error={errors.socials}>
						<SocialMediaEntry key={field.id} index={index} />
					</FormField>
				))}
			</div>
		</section>
	)
}

const SocialMediaEntry = ({ index }: { index: number }) => {
	const { register, watch, remove } = useArtistFormContext()
	const Icon = socialUrlToIcon(watch(`socials.${index}.value`))

	return (
		<div className="w-full flex gap-4 items-center">
			<div className="relative w-full">
				<Icon className="absolute right-4 top-1/2 -translate-y-1/2 text-text/50" />
				<Input {...register(`socials.${index}.value`)} />
			</div>
			<button onClick={() => remove(index)} type="button" className=" text-text/50 hover:text-text h-full"><FaTrash /></button>
		</div>
	)
}

export default ArtistForm

// frontend/src/routes/admin/artists/ArtistForm.svelte
<script lang="ts">
	import type { z } from 'zod';

	import { createArtistForm, editArtistForm, type Artist } from '$lib/features/artist/artist';
	import { trackIdFromUrl } from '$lib/features/artist/spotify';

	import type { Genre } from '$lib/features/artist/genre';

	import Input from '$lib/components/ui/Input.svelte';
	import Button from '$lib/components/ui/Button.svelte';
	import ImagePreview from '$lib/components/ImagePreview.svelte';
	import Pill from '$lib/components/Pill.svelte';
	import GenreSelectorModal from '$lib/components/GenreSelectorModal.svelte';
	import SpotifyPreview from '$lib/components/SpotifyPreview.svelte';

	import PublishIcon from '~icons/mdi/upload';
	import PlusIcon from '~icons/mdi/add';

	import TipTapEditor from '$lib/components/tiptap/TipTapEditor.svelte';
	import Spinner from '$lib/components/Spinner.svelte';
	import FormField from '$lib/components/ui/FormField.svelte';
	import SocialList from './SocialList.svelte';

	type Props = {
		artist?: Artist;

		genres: Genre[];

		errors:
			| z.typeToFlattenedError<z.infer<typeof createArtistForm> | z.infer<typeof editArtistForm>>
			| undefined;

		loading: boolean;
		onSubmit: (form: z.infer<typeof createArtistForm> | z.infer<typeof editArtistForm>) => void;
	};

	let { artist, genres, loading, errors, onSubmit }: Props = $props();

	let form = $state<z.infer<typeof createArtistForm> | z.infer<typeof editArtistForm>>(
		artist
			? {
					name: artist.name,
					description: artist.description,
					previewUrl: artist.previewUrl || '',
					genreIds: artist.genres.map((genre) => genre.id),
					image: null,
					socials: artist.socials
				}
			: {
					name: '',
					description: '',
					previewUrl: '',
					genreIds: [],
					socials: [],
					image: null
				}
	);

	let socialUrl = $state('');
	let selectedGenres = $derived(genres.filter((genre) => form.genreIds.includes(genre.id)));

	let showGenreModal = $state(false);

	let imageUrl = $derived(form.image ? URL.createObjectURL(form.image) : artist?.imageUrl || '');

	let trackId = $derived(form.previewUrl ? trackIdFromUrl(form.previewUrl) : undefined);

	const updateImage = (file: File | null) => {
		if (!file) return;

		form.image = file;
	};

	const addSocial = () => {
		// Return if already exists.
		if (form.socials.some((social) => social === socialUrl)) return;

		form.socials = [...form.socials, socialUrl];
		socialUrl = '';
	};

	const submit = (e: SubmitEvent) => {
		e.preventDefault();

		onSubmit(form);
	};
</script>

<form class="w-full max-w-3xl space-y-16" onsubmit={submit}>
	<h1 class="font-heading mb-8 text-4xl font-bold">
		{#if artist}
			Redigér kunstner
		{:else}
			Lav kunstner
		{/if}
	</h1>
	<div class="space-y-8">
		<FormField errors={errors?.fieldErrors.image}>
			<ImagePreview accept="image/jpeg,image/png" src={imageUrl} onChange={updateImage} />
		</FormField>
		<div class="space-y-8">
			<div class="space-y-1">
				<FormField errors={errors?.fieldErrors.name}>
					<Input placeholder="Kunstnernavn" bind:value={form.name} />
				</FormField>
			</div>
			<div class="space-y-1">
				<FormField errors={errors?.fieldErrors.description}>
					<TipTapEditor bind:value={form.description} />
				</FormField>
			</div>
		</div>
	</div>

	<div>
		<h1 class="font-heading mb-8 text-2xl font-bold">Genrer</h1>
		<div class="mb-2 flex flex-wrap gap-2">
			<button
				type="button"
				onclick={() => (showGenreModal = true)}
				class="flex items-center gap-2 rounded-full border border-zinc-900 px-4 py-2 hover:border-zinc-800 hover:bg-zinc-900"
			>
				<PlusIcon />Tilføj
			</button>
			<ul class="flex flex-wrap gap-2">
				{#each selectedGenres as genre (genre.id)}
					<Pill>{genre.name}</Pill>
				{/each}
			</ul>
		</div>
		<FormField errors={errors?.fieldErrors.genreIds}>
			<GenreSelectorModal
				{genres}
				bind:show={showGenreModal}
				onChange={(selected) => (form.genreIds = selected.map((genre) => genre.id))}
			/>
		</FormField>
	</div>

	<div class="flex flex-col">
		<h1 class="font-heading mb-8 text-2xl font-bold">Spotify Preview</h1>
		<div class="space-y-4">
			<FormField errors={errors?.fieldErrors.previewUrl}>
				<Input placeholder="Preview-URL" bind:value={form.previewUrl} />
				{#if trackId}
					<SpotifyPreview {trackId} />
				{/if}
			</FormField>
		</div>
	</div>

	<div class="flex flex-col">
		<h1 class="font-heading mb-4 text-2xl font-bold">Sociale medier</h1>
		<div class="mb-4 flex w-full gap-2">
			<FormField errors={errors?.fieldErrors.socials}>
				<Input type="text" placeholder="URL" bind:value={socialUrl} class="flex-1" />
			</FormField>
			<Button type="button" onclick={addSocial}><PlusIcon />Tilføj</Button>
		</div>
		<SocialList bind:socials={form.socials} />
	</div>
	<Button type="submit">
		{#if loading}
			<Spinner />
			Offentligører...
		{:else}
			<PublishIcon />
			Offentligør
		{/if}
	</Button>
</form>
