// frontend/src/routes/admin/artists/create/+page.svelte
<script lang="ts">
	import { createArtist, createArtistForm } from '$lib/features/artist/artist';
	import { ZodError, type z } from 'zod';
	import ArtistForm from '../ArtistForm.svelte';
	import { toaster } from '$lib/toaster.svelte';
	import { goto } from '$app/navigation';

	let { data } = $props();

	let errors = $state<z.typeToFlattenedError<z.infer<typeof createArtistForm>>>();
	let loading = $state(false);

	const handleSubmit = async (form: z.infer<typeof createArtistForm>) => {
		try {
			loading = true;
			await createArtist(fetch, form);
			toaster.addToast('Kunstner skabt');
			await goto('/admin/artists');
			loading = false;
		} catch (e) {
			if (e instanceof ZodError) {
				toaster.addToast('Kunne ikke skabe kunstner', 'Ugyldig kunstnerdata', 'error');
				errors = e.flatten();
				loading = false;
				return;
			}

			toaster.addToast('Kunne ikke skabe kunstner', 'Noget gik galt...', 'error');
			loading = false;
			throw e;
		}
	};
</script>

<main class="px-8 py-16 md:px-16">
	<ArtistForm {loading} genres={data.genres} onSubmit={handleSubmit} {errors} />
</main>

// frontend/src/routes/admin/artists/create.tsx
import { APIError } from '@/lib/api'
import ArtistForm from '@/lib/components/artist-form'
import { useToast } from '@/lib/context/toast'
import { createArtist, type createArtistForm } from '@/lib/features/artist'
import { useGenres } from '@/lib/features/hook'
import { useQueryClient } from '@tanstack/react-query'
import { createFileRoute, useNavigate } from '@tanstack/react-router'
import type { z } from 'zod'

export const Route = createFileRoute('/admin/artists/create')({
  component: RouteComponent,
})

function RouteComponent() {
  const { addToast } = useToast()
  const navigate = useNavigate()
  const queryClient = useQueryClient()

  const genreQuery = useGenres()

  const genres = genreQuery.data?.records || []

  const onSubmit = async (form: z.infer<typeof createArtistForm>) => {
    try {
      await createArtist(form)
      addToast("Kunstner lavet")
      await queryClient.invalidateQueries({ queryKey: ["artists"] })
      navigate({ to: "/admin/artists" })
    } catch (e) {
      if (e instanceof APIError) {
        addToast("Kunne ikke lave kunstner", e.message, "error")
        throw e
      }

      addToast("Kunne ikke lave kunstner", "Noget gik galt...", "error")
      throw e
    }
  }

  return (
    <ArtistForm genres={genres} onSubmit={onSubmit} />
  )
}
