// frontend/src/routes/admin/artists/+page.svelte
<script lang="ts">
	import Button from '$lib/components/ui/Button.svelte';
	import PlusIcon from '~icons/mdi/plus';
	import { hasPermissions } from '$lib/features/auth/permission';
	import ArtistList from './ArtistList.svelte';
	import DashboardLayout from '../DashboardLayout.svelte';
	import DashboardHeader from '../DashboardHeader.svelte';
	import HeaderActions from '../HeaderActions.svelte';
	import { authStore } from '$lib/auth.svelte';

	let { data } = $props();
</script>

<DashboardLayout>
	<DashboardHeader
		title="Kunstnere"
		description="Overblik over alle kunstnere, som er associerede med events."
	>
		<HeaderActions>
			<Button
				href="/admin/artists/create"
				disabled={!hasPermissions(authStore.permissions, ['edit:artist'])}
			>
				<PlusIcon />Tilføj
			</Button>
		</HeaderActions>
	</DashboardHeader>

	{#if hasPermissions(authStore.permissions, ['view:artist'])}
		<section class="space-y-4">
			<ArtistList artists={data.artists} upcomingArtists={data.upcomingArtists} />
		</section>
	{:else}
		<span>Du har ikke tilladelse til at se kunstnere...</span>
	{/if}
</DashboardLayout>

// frontend/src/routes/admin/artists/index.tsx
import AdminHeader from '@/lib/components/admin-header'
import LinkButton from '@/lib/components/ui/button/link-button'
import { useAuth } from '@/lib/context/auth'
import ArtistList from '@/lib/features/artist/components/artist-list'
import { artistsQueryOpts, upcomingArtistsQueryOpts } from '@/lib/features/artist/query'
import { useSuspenseQuery } from '@tanstack/react-query'
import { createFileRoute } from '@tanstack/react-router'
import { FaPlus } from 'react-icons/fa6'

export const Route = createFileRoute('/admin/artists/')({
  component: RouteComponent,
  loader: async ({ context: { queryClient } }) => {
    queryClient.ensureQueryData(upcomingArtistsQueryOpts)
    queryClient.ensureQueryData(artistsQueryOpts)
  }
})

function RouteComponent() {
  const { data: upcomingArtists } = useSuspenseQuery(upcomingArtistsQueryOpts)
  const { data: { records: artists } } = useSuspenseQuery(artistsQueryOpts)

  const { hasPermissions } = useAuth()

  return (
    <>
      <AdminHeader>
        <AdminHeader.Title>Kunstnere</AdminHeader.Title>
        <AdminHeader.Description
        >Overblik over alle kunstnere, som er associerede med events.</AdminHeader.Description
        >
        <AdminHeader.Actions>
          <LinkButton
            to="/admin/artists/create"
            disabled={!hasPermissions(['edit:artist'])}
          >
            <FaPlus />Tilføj
          </LinkButton>
        </AdminHeader.Actions>
      </AdminHeader>

      <main className="pt-16">
        {hasPermissions(['view:artist']) ? (
          <section className="space-y-4">
            <ArtistList
              artists={artists}
              upcomingArtists={upcomingArtists}
            />
          </section>
        ) : (
          <span>Du har ikke tilladelse til at se kunstnere...</span>

        )}
      </main>
    </>
  )
}
