// frontend/src/routes/admin/artists/edit/ArtistForm.svelte
<script lang="ts">
	import type { ZodError } from 'zod';

	import { artistFormSchema, type Artist, type ArtistForm } from '$lib/artist';
	import { trackIdFromUrl } from '$lib/spotify';

	import type { Genre } from '$lib/genre';

	import Input from '$lib/components/ui/Input.svelte';
	import FieldError from '$lib/components/ui/FieldError.svelte';
	import Button from '$lib/components/ui/Button.svelte';
	import ImagePreview from '$lib/components/ui/ImagePreview.svelte';
	import Pill from '$lib/components/ui/Pill.svelte';
	import GenreSelectorModal from '$lib/components/ui/GenreSelectorModal.svelte';
	import SpotifyPreview from '$lib/components/SpotifyPreview.svelte';
	import SocialEntry from './SocialEntry.svelte';

	import PlusIcon from '~icons/mdi/add';

	type Props = {
		artist: Artist | null;
		genres: Genre[];
		onSubmit: (form: ArtistForm) => void;
	};

	let { artist, genres, onSubmit }: Props = $props();

	let form: ArtistForm = $state({
		name: artist?.name || '',
		description: artist?.description || '',
		previewUrl: artist?.previewUrl || '',
		genreIds: artist?.genres.map((genre) => genre.id) || [],
		image: null,
		socials: artist?.socials || []
	});

	let socialUrl = $state('');
	let selectedGenres = $derived(genres.filter((genre) => form.genreIds.includes(genre.id)));

	let showGenreModal = $state(false);
	let formError = $state<ZodError | null>(null);

	let imageUrl = $derived(form.image ? URL.createObjectURL(form.image) : artist?.imageUrl || '');

	let trackId = $derived(artist?.previewUrl ? trackIdFromUrl(form.previewUrl) : '');

	const updateImage = (file: File | null) => {
		if (!file) return;

		form.image = file;
	};

	const addSocial = () => {
		// Return if already exists.
		if (form.socials.some((social) => social === socialUrl)) return;

		form.socials = [...form.socials, socialUrl];
	};

	const submit = (e: SubmitEvent & { currentTarget: EventTarget & HTMLFormElement }) => {
		e.preventDefault();

		const { data, success, error } = artistFormSchema.safeParse(form);
		if (!success) {
			formError = error;
			return;
		}

		onSubmit(data);
	};
</script>

<form class="w-full max-w-xl space-y-16" onsubmit={submit}>
	<div class="space-y-8">
		<h1 class="mb-8 text-2xl font-bold">Generelt</h1>
		<ImagePreview src={imageUrl} onChange={updateImage} />
		<div class="space-y-8">
			<div class="space-y-1">
				<Input
					label="Kunstnernavn"
					bind:value={form.name}
					errors={formError?.flatten().fieldErrors['name']}
				/>
			</div>
			<div class="space-y-1">
				<Input
					label="Beskrivelse"
					bind:value={form.description}
					errors={formError?.flatten().fieldErrors['description']}
				/>
			</div>
		</div>
	</div>

	<div>
		<h1 class="mb-4 text-2xl font-bold">Genrer</h1>
		<div class="mb-2 flex flex-wrap gap-2">
			<button
				type="button"
				onclick={() => (showGenreModal = true)}
				class="flex items-center gap-2 rounded-full border border-zinc-900 px-4 py-2 hover:border-zinc-800 hover:bg-zinc-900"
			>
				<PlusIcon />Tilføj
			</button>
			{#each selectedGenres as genre (genre.id)}
				<Pill>{genre.name}</Pill>
			{/each}
		</div>
		<FieldError errors={formError?.flatten().fieldErrors['genreIds']} />
		<GenreSelectorModal
			{genres}
			show={showGenreModal}
			onClose={() => (showGenreModal = false)}
			onChange={(selected) => (form.genreIds = selected.map((genre) => genre.id))}
		/>
	</div>

	<div class="flex flex-col gap-4">
		<h1 class="mb-8 text-2xl font-bold">Spotify Preview</h1>
		<div class="space-y-4">
			<Input label="Preview URL" bind:value={form.previewUrl} />
			{#if trackId}
				<SpotifyPreview {trackId} />
			{/if}
		</div>
	</div>
	<div class="space-y-4">
		<h1 class="mb-8 text-2xl font-bold">Sociale medier</h1>
		<div class="mb-4 flex w-full gap-2">
			<Input type="text" label="URL" bind:value={socialUrl} class="flex-1" />
			<Button type="button" onclick={addSocial}><PlusIcon />Tilføj</Button>
		</div>
		<div class="space-y-2">
			{#each form.socials as url (url)}
				<SocialEntry
					{url}
					onChange={(newUrl) =>
						(form.socials = form.socials.map((social) => (social === url ? newUrl : social)))}
					onDelete={() => (form.socials = form.socials.filter((social) => social !== url))}
				/>
			{/each}
		</div>
		<FieldError errors={formError?.flatten().fieldErrors['socials']} />
	</div>
	<Button type="submit" expandX>Offentligør</Button>
</form>

// frontend/src/lib/components/artist-form.tsx
import { createContext, useContext, useState } from "react"
import { z } from "zod"

import { FormProvider, useFieldArray, useForm, type UseFieldArrayReturn, type UseFormReturn } from "react-hook-form"
import { zodResolver } from "@hookform/resolvers/zod"

import { createArtistForm, editArtistForm, socialUrlToIcon, type Artist } from "../features/artist"
import type { Genre } from "../features/genre"
import { trackIdFromUrl } from "../spotify"

import FormField from "./form-field"
import Input from "./ui/input"
import Button from "./ui/button/button"
import Picker, { type Entry } from "./ui/picker"
import PillList from "./pill-list"
import ImagePreview from "./image-preview"
import Tiptap from "./tiptap/tiptap"
import SpotifyPreview from "./spotify-preview"

import { FaPlus, FaTrash, FaUpload, FaPen } from "react-icons/fa"

const artistForm = z.union([createArtistForm, editArtistForm])
type ArtistForm = z.infer<typeof artistForm>

const internalSocialSchema = z.object({ value: z.string().url() })

const internalArtistFormSchema = z.union([
	createArtistForm
		.omit({ socials: true })
		.extend({ socials: internalSocialSchema.array() }),
	editArtistForm
		.omit({ socials: true })
		.extend({ socials: internalSocialSchema.array() }),
])

type InternalArtistForm = z.infer<typeof internalArtistFormSchema>

type ArtistFormContext =
	UseFormReturn<InternalArtistForm> &
	UseFieldArrayReturn<InternalArtistForm> & {
		artist: Artist | undefined;
		genres: Genre[]
	}

const ArtistFormContext = createContext<ArtistFormContext | undefined>(undefined)

export const useArtistFormContext = () => {
	const ctx = useContext(ArtistFormContext)
	if (!ctx) throw new Error("No Provider for ArtistFormContext")
	return ctx
}

type Props = {
	artist?: Artist;
	genres: Genre[]

	onSubmit: (form: ArtistForm) => void;
}

const ArtistForm = ({ artist, genres, onSubmit }: Props) => {
	const methods = useForm<InternalArtistForm>({
		defaultValues: {
			...artist,
			genreIds: artist?.genres.map(genre => genre.id) || [],
			socials: artist?.socials.map(s => ({ value: s }))
		},
		resolver: zodResolver(internalArtistFormSchema),
	})

	const { control, formState: { errors }, register, watch, handleSubmit, setValue } = methods
	const fieldArrayMethods = useFieldArray({ control, name: "socials" })

	const submitForm = (form: InternalArtistForm) => {
		const output: ArtistForm = {
			...form,
			socials: form.socials.map(v => v.value)
		}

		const { data, success, error } = artistForm.safeParse(output)
		if (!success) {
			console.error(error)
			throw error
		}

		onSubmit(data)
	}

	return (
		<ArtistFormContext.Provider value={{ ...methods, ...fieldArrayMethods, artist, genres }}>
			<FormProvider {...methods}>
				<form className="flex flex-col gap-16" onSubmit={handleSubmit(submitForm)}>
					<FormField error={errors.image}>
						<ImagePreview
							src={artist?.imageUrl}
							accept="image/jpeg,image/png"
							onChange={(file) => setValue("image", file)}
						/>
					</FormField>

					<GeneralSection />
					<SpotifySection />
					<GenreSection />
					<SocialsSection />

					<Button type="submit" className="w-full md:w-fit"><FaUpload />Offentligør</Button>
				</form>
			</FormProvider>
		</ArtistFormContext.Provider>
	)
}

const GeneralSection = () => {
	const { register, setValue, formState: { errors, defaultValues } } = useArtistFormContext()

	return (
		<section >
			<h1 className="font-heading text-2xl font-bold mb-4">Generelt</h1>
			<div className="flex flex-col gap-4">
				<FormField error={errors.name}>
					<Input placeholder="Kunstnernavn" {...register("name")} />
				</FormField>

				<FormField error={errors.description}>
					<Tiptap
						content={defaultValues?.description}
						onChange={(html) => setValue("description", html)}
					/>
				</FormField>
			</div>
		</section>
	)

}

const SpotifySection = () => {
	const { register, watch } = useArtistFormContext()

	const trackId = trackIdFromUrl(watch("previewUrl"))

	return (
		<section>
			<h1 className="text-2xl font-bold font-heading mb-8">Spotify Preview</h1>
			<div className="flex flex-col gap-4">
				<Input placeholder="Spotify Preview-URL..." {...register("previewUrl")} />
				{trackId && <SpotifyPreview trackId={trackId} />}
			</div>
		</section>
	)
}

const GenreSection = () => {
	const { genres, setValue, formState: { errors }, watch } = useArtistFormContext()
	const [showPicker, setShowPicker] = useState(false)

	const entries: Entry[] = genres.map(genre => ({
		id: genre.id.toString(),
		value: genre.id.toString(),
		name: genre.name,
	}))

	const selected = entries.filter(entry =>
		watch("genreIds").includes(parseInt(entry.value))
	)

	return (
		<section>
			<h1 className="font-bold font-heading mb-8 text-2xl">Genrer</h1>

			<FormField error={errors.genreIds}>
				<PillList entries={selected.map(entry => entry.name)}>
					<Button variant="ghost" onClick={() => setShowPicker(true)} className="h-10 rounded-full px-4" ><FaPen />Vælg</Button>
				</PillList>
			</FormField>

			<Picker
				title="Vælg genrer..."
				description="Her kan du vælge de genrer, som kunstneren associeres med."
				entries={entries}
				selected={selected}
				show={showPicker}
				onClose={() => setShowPicker(false)}
				onChange={(selectedEntries) =>
					setValue("genreIds", selectedEntries.map(entry => parseInt(entry.value)))
				}
			/>
		</section>
	)
}

const SocialsSection = () => {
	const { fields, formState: { errors }, append } = useArtistFormContext()

	const [input, setInput] = useState("")

	return (
		<section>
			<h1 className="font-heading font-bold text-2xl mb-4">Sociale medier</h1>

			<div className="w-full flex gap-4 mb-8">
				<Input placeholder="URL..." value={input} onChange={e => setInput(e.target.value)} />
				<Button variant="secondary" onClick={() => append({ value: input })}><FaPlus /> Tilføj</Button>
			</div>

			<div className="flex flex-col gap-2">
				{fields.map((field, index) => (
					<FormField error={errors.socials}>
						<SocialMediaEntry key={field.id} index={index} />
					</FormField>
				))}
			</div>
		</section>
	)
}

const SocialMediaEntry = ({ index }: { index: number }) => {
	const { register, watch, remove } = useArtistFormContext()
	const Icon = socialUrlToIcon(watch(`socials.${index}.value`))

	return (
		<div className="w-full flex gap-4 items-center">
			<div className="relative w-full">
				<Icon className="absolute right-4 top-1/2 -translate-y-1/2 text-text/50" />
				<Input {...register(`socials.${index}.value`)} />
			</div>
			<button onClick={() => remove(index)} type="button" className=" text-text/50 hover:text-text h-full"><FaTrash /></button>
		</div>
	)
}

export default ArtistForm
