// frontend/app/routes/events.$id/event-caroussel.tsx
import { EventCard } from "~/components/events/event-card"
import { EventDTO } from "~/lib/event/event.dto"

type Props = {
  events: EventDTO[]
}

export const EventCaroussel = ({ events }: Props) => {
  return (
    <div className="relative flex gap-8 items-center overflow-x-scroll snap-x w-full pb-4">
      {events.map(event => {
        return (
          <div key={event.id} className="scroll-pl-2 h-full sm:w-72 md:w-96 flex-shrink-0 snap-center">
            <EventCard event={event} />
          </div>
        )
      })}
      <div className="h-64 w-16 flex-shrink-0 snap-center flex justify-center items-center">
        <a href="/events" className="w-full text-center">Se alle.</a>
      </div>
    </div>
  )
}

// frontend/src/lib/components/EventCaroussel.svelte
<script lang="ts">
	import type { Event } from '$lib/event';
	import EventCard from './EventCard.svelte';

	type Props = {
		title?: string;
		events: Event[];
	};

	let { events, title = 'Events.' }: Props = $props();
</script>

<h3 class="mb-4 text-2xl font-bold">{title}</h3>
<div class="flex gap-2">
	{#each events as event (event.id)}
		<EventCard {event} />
	{/each}
</div>
