// frontend/app/components/events/event-grid.tsx
import { EventDTO } from "~/lib/event/event.dto"
import { EventCard } from "./event-card"
import { cn } from "~/lib/utils";

type Props = {
  events: EventDTO[]
  className?: string;
}

export const EventGrid = ({ events, className }: Props) => {
  return (
    <div className={cn("grid grid-cols-1 md:grid-cols-2 gap-4", className)}>
      {events.map(event => <EventCard key={event.id} event={event} />)}
    </div>
  )
}

// frontend/src/lib/components/EventGrid.svelte
<script lang="ts">
	import type { Event } from "$lib/features/event";
	import EventEntry from "./EventEntry.svelte";

	type Props = {
		events: Event[];
	};

	let { events }: Props = $props();
</script>

<div class="@container">
	<div class="grid grid-cols-1 gap-4 @2xl:grid-cols-2 @5xl:grid-cols-3 @7xl:grid-cols-4">
		{#each events as event}
			<EventEntry {event} />
		{/each}
	</div>
</div>
