// frontend/src/lib/components/file-picker.tsx
import type { InputHTMLAttributes } from "react";
import { cn } from "../clsx";

type Props = Omit<InputHTMLAttributes<HTMLInputElement>, "onChange"> & {
	onChange: (files: FileList | null) => void;
};

const FilePicker = ({ onChange, className, ...rest }: Props) => (
	<input
		{...rest}
		type="file"
		className={cn(
			'text-text file:rounded-md file:bg-zinc-100 file:px-4 file:py-2 file:font-medium file:text-zinc-900',
			className
		)}
		onChange={(e) => onChange(e.currentTarget.files)}
	/>
)

export default FilePicker

// frontend/src/lib/components/FilePicker.svelte
<script lang="ts">
	import { cn } from '$lib/clsx';
	import type { HTMLAttributes } from 'svelte/elements';

	type Props = HTMLAttributes<HTMLInputElement> & {
		onChange: (files: FileList | null) => void;
	};

	let { onChange, ...rest }: Props = $props();
</script>

<input
	{...rest}
	type="file"
	class={cn(
		'text-text file:rounded-md file:bg-zinc-100 file:px-4 file:py-2 file:font-medium file:text-zinc-900',
		rest.class
	)}
	onchange={(e) => onChange(e.currentTarget.files)}
/>
