// frontend/app/components/ui/file-picker.tsx
import { ChangeEvent, forwardRef } from "react";
import { cn } from "~/lib/utils";

type Props = {
  name: string;
  multiple?: boolean;
  accept?: string;
  className?: string;
  onChange: (file: FileList) => void;
}

export const FilePicker = forwardRef<HTMLInputElement, Props>(({ name, multiple, accept, onChange, className }: Props, ref) => {
  const changeFile = (e: ChangeEvent<HTMLInputElement>) => {
    const files = e.currentTarget.files

    if (!files) return

    onChange(files)
  }

  return (
    <div className={cn("flex flex-col gap-1", className)}>
      <input
        ref={ref}
        name={name}
        type="file"
        multiple={multiple}
        accept={accept}
        className="file:bg-foreground file:text-background file:px-2 file:py-1 
        file:border-none file:rounded-md file:font-medium"
        onChange={changeFile}
      />
    </div>
  )
})

// frontend/src/lib/components/FilePicker.svelte
<script lang="ts">
	import { cn } from '$lib/clsx';
	import type { HTMLAttributes } from 'svelte/elements';

	type Props = HTMLAttributes<HTMLInputElement> & {
		onChange: (files: FileList | null) => void;
	};

	let { onChange, ...rest }: Props = $props();
</script>

<input
	{...rest}
	type="file"
	class={cn(
		'text-text file:rounded-md file:bg-zinc-100 file:px-4 file:py-2 file:font-medium file:text-zinc-900',
		rest.class
	)}
	onchange={(e) => onChange(e.currentTarget.files)}
/>
