// frontend/src/lib/components/form-field.tsx
import { cn } from "@/lib/clsx";
import type { PropsWithChildren } from "react";
import type { FieldError } from "react-hook-form";

type Props = PropsWithChildren<{
	error?: FieldError | undefined
}>;

const FormField = ({ error, children }: Props) => (
	<div className="flex w-full flex-col gap-2">
		<div className="flex gap-4">
			{children}
		</div>

		{error && (
			<span className={cn("text-sm hidden text-red-500", { "block": error })}>
				{error?.message}
			</span>
		)}
	</div>
)

export default FormField

// frontend/src/lib/components/FormField.svelte
<script lang="ts">
	import type { WithChildren, WithClass } from "$lib/class";
	import ErrorList from "./ErrorList.svelte";

	type Props = (WithClass & WithChildren) & {
		issues?: string[] | undefined;
	};

	let { issues, children, ...rest }: Props = $props();
</script>

<div class={["flex w-full flex-col gap-2", rest.class]}>
	{@render children?.()}

	{#if issues && issues.length > 0}
		<ErrorList {issues} />
	{/if}
</div>
