// frontend/src/lib/components/member-display.tsx
import type { Member } from "@/lib/features/auth/member"

type Props = {
	members: Member[];
}

const TeamDisplay = ({ members }: Props) => {
	return (
		<div>
			{members.map(({ firstName, lastName, email, avatarUrl, teams, specialRole }) => (
				<div className="@container group isolate">
					<div className="flex flex-col @xl:flex-row relative border border-zinc-900 overflow-hidden rounded-sm transition-colors duration-600 group-hover:border-zinc-800">
						<img src={avatarUrl} className="z-10 max-h-80 @xl:h-32 @xl:aspect-square @xl:w-auto w-full object-cover group-hover:brightness-105 transition-[filter]" />
						<img src={avatarUrl} className="-z-50 absolute top-0 left-0 h-full w-full object-cover opacity-0 blur-2xl scale-150 transition-opacity duration-300 group-hover:opacity-5" />

						<div className="p-4 flex flex-col z-20">
							<span className="text-heading font-semibold mb-2">{firstName} {lastName}</span>
							<span>{specialRole ?? teams.map(({ displayName }) => displayName).join(", ")}</span>
							<a href={`mailto:${email}`} className="hover:underline hover:text-heading">{email}</a>
						</div>
					</div>
				</div>
			))}
		</div>
	)
}

export default TeamDisplay;

// frontend/src/lib/components/MemberDisplay.svelte
<script lang="ts">
	import type { Member, Team, TeamType } from "$lib/features/auth/auth";
	import { getTeams } from "$lib/features/auth/auth.remote";

	const includedTeamNames: TeamType[] = [
		"project-leader",
		"public-relations",
		"event-management",
		"booking",
		"visual-identity",
		"economy"
	];

	type Props = {
		members: Member[];
	};

	let { members }: Props = $props();

	const { items: teams } = $derived(await getTeams(undefined));

	const includedTeams = $derived(teams.filter((team) => includedTeamNames.includes(team.name)));

	const includedMembers = $derived(
		members.filter((member) =>
			member.teams.some((team) =>
				includedTeams.some((includedTeam) => includedTeam.name === team.name)
			)
		)
	);

	const specialMembers = $derived(includedMembers.filter((member) => member.specialRole));
	const regularMembers = $derived(includedMembers.filter((member) => !member.specialRole));

	const extractValidTeamNames = (teams: Team[]) => {
		return teams
			.filter((team) => includedTeams.some((t) => t.name === team.name))
			.map((t) => t.name);
	};
</script>

<div class="@container flex flex-col">
	<div class="mb-16 grid grid-cols-1 gap-2 @3xl:grid-cols-2">
		{#each specialMembers as { firstName, lastName, avatar, specialRole, teams }}
			<div
				class="group flex items-center overflow-hidden rounded-full border border-zinc-800 bg-zinc-900 p-1 transition-colors"
			>
				<img
					src={avatar}
					alt="{firstName} {lastName}"
					class="aspect-square w-24 shrink-0 rounded-full object-cover @lg:w-32"
				/>
				<div class="h-mi flex w-full flex-col gap-2 overflow-hidden px-8 py-4">
					<span class="line-clamp-1 font-medium text-text-light @lg:text-xl">
						{firstName}
						{lastName}
					</span>
					<div class="w-full">
						<span class="line-clamp-1">
							{#if specialRole}
								{specialRole}
							{:else}
								{extractValidTeamNames(teams).join(", ")}
							{/if}
						</span>
					</div>
				</div>
			</div>
		{/each}
	</div>

	{#if regularMembers.length > 0}
		<h4 class="text-text/50 mb-12 text-center">
			Øvrige {#if regularMembers.length > 5}{regularMembers.length}{/if} medlemmer
		</h4>
	{/if}

	<div class="flex flex-wrap justify-center gap-x-20 gap-y-12">
		{#each regularMembers as member}
			{@const memberTeams = member.teams.filter((team) =>
				includedTeams.some((t) => t.name === team.name)
			)}
			{@const teamsString = memberTeams.map((t) => t.displayName).join(", ")}

			<div class="flex flex-col items-center">
				<p class="mb-1 text-base font-medium">
					{member.firstName}
					{member.lastName}
				</p>
				<p class="text-text/50 text-xs">{teamsString}</p>
			</div>
		{/each}
	</div>
</div>
