// frontend/app/navbar.tsx
export const Navbar = () => {
  return (
    <nav className="bg-background h-nav flex items-center px-8 border-b border-gray-950 justify-between">
      <a href="/" className="font-black">KONNEKT&reg;</a>
      <ul className="flex gap-4">
        <li><a href="/events">Events</a></li>
        <li><a href="/om-os">Om os</a></li>
        <li><a href="/sponsorer">Sponsorer</a></li>
      </ul>
    </nav>
  )
}

// frontend/src/lib/components/Navbar.svelte
<nav class="h-nav bg-background text-text flex items-center justify-between px-8">
	<h3 class="font-black">KONNEKT</h3>

	<ul class="text-text/80 *:hover:text-text flex space-x-5 font-medium">
		<li><a href="/events">Events</a></li>
		<li><a href="/artists">Artister</a></li>
		<li><a href="/sponsorer">Sponsorer</a></li>
	</ul>
</nav>
