// frontend/src/lib/components/ProfilePictureSelector.svelte
<script lang="ts">
	import AvatarImage from '$lib/assets/avatar.png';

	type Props = {
		imageUrl?: string;
		file: File | null;
	};

	let { imageUrl, file = $bindable(null) }: Props = $props();

	let fileInput: HTMLInputElement;

	const onFileChange = (e: Event & { currentTarget: EventTarget & HTMLInputElement }) => {
		if (!e.currentTarget.files) return;

		const newFile = e.currentTarget.files.item(0);

		changeImage(newFile);
	};

	const changeImage = (newFile: File | null) => {
		if (!newFile) {
			file = null;
			imageUrl = '';
			return;
		}

		file = newFile;
		imageUrl = URL.createObjectURL(newFile);
	};
</script>

<div class="relative w-fit">
	<input hidden bind:this={fileInput} type="file" onchange={onFileChange} />
	<img src={imageUrl || AvatarImage} alt="Profile" class="h-28 w-28 rounded-full object-cover" />
	<button
		onclick={() => fileInput.click()}
		type="button"
		class="bg-text absolute right-0 bottom-0 translate-x-1/2 translate-y-1/2 rounded-sm px-2 py-1 text-sm text-zinc-950 shadow-sm"
		>Vælg</button
	>
</div>

// frontend/src/lib/components/profile-picture-selector.tsx
import AvatarImage from '@/lib/assets/avatar.png';
import { useRef, useState, type ChangeEvent, type InputHTMLAttributes } from 'react';

type Props = {
	src?: string;
	onChange: (newFile: File) => void;
	file?: File | null | undefined
	accept?: InputHTMLAttributes<HTMLInputElement>["accept"]
};

const ProfilePictureSelector = ({ accept = "image/jpeg,image/png", file, onChange }: Props) => {
	const [src, setSrc] = useState(() => file ? URL.createObjectURL(file) : undefined)

	const ref = useRef<HTMLInputElement>(null)

	const onFileChange = (e: ChangeEvent<HTMLInputElement>) => {
		if (!e.target.files) return;
		const newFile = e.target.files.item(0);
		if (!newFile) return

		changeImage(newFile);
	};

	const changeImage = (newFile: File) => {
		setSrc(URL.createObjectURL(newFile))
		onChange(newFile)
	};

	return (
		<div className="relative w-fit">
			<input ref={ref} hidden accept={accept} type="file" onChange={onFileChange} />
			<img src={src || AvatarImage} alt="Profile" className="h-28 w-28 rounded-full object-cover" />
			<button
				type="button"
				onClick={() => ref.current?.click()}
				className="bg-text absolute right-0 bottom-0 translate-x-1/2 translate-y-1/2 rounded-sm px-2 py-1 text-sm text-zinc-950 shadow-sm"
			>
				Vælg
			</button>
		</div>
	)
}

export default ProfilePictureSelector
