// frontend/src/lib/components/SearchList.svelte
<script lang="ts">
	import type { WithChildren } from '$lib/types';
	import SearchBar from './SearchBar.svelte';
	import List from './ui/List.svelte';

	type Props = WithChildren<{
		search: string;
	}>;

	let { search = $bindable(''), children }: Props = $props();
</script>

<div class="flex flex-col gap-8">
	<SearchBar bind:value={search} />
	<List>
		{@render children?.()}
	</List>
</div>

// frontend/src/lib/components/search-list.tsx
import type { PropsWithChildren } from "react";
import Searchbar from "./searchbar";
import List from "./list/list";

type Props = PropsWithChildren<{
  search: string;
  onChange: (newSearch: string) => void;
}>;

const SearchList = ({ search, onChange, children }: Props) => (
  <div className="flex flex-col gap-8">
    <Searchbar search={search} onChange={onChange} />
    <List>{children}</List>
  </div>
);

export default SearchList;
