// frontend/src/lib/components/SponsorDisplay.svelte
<script lang="ts">
	type Props = {
		srcs: { src: string; href: string; title: string }[];
	};

	let { srcs }: Props = $props();
</script>

<div
	class="flex flex-wrap justify-center gap-12 bg-radial from-zinc-900 to-background to-75% p-8 sm:p-16"
>
	{#each srcs as { title, src, href }}
		<a aria-label={title} {href} class="group flex w-20 items-center justify-center sm:w-24">
			<img
				{src}
				alt={title}
				loading="lazy"
				class="aspect-square transition-[filter,scale] group-hover:brightness-100 md:brightness-60"
			/>
		</a>
	{/each}
</div>

// frontend/src/lib/components/sponsor-display.tsx
type Src = {
	src: string;
	alt: string;
}

type Props = {
	srcs: Map<string, Src>
}

const SponsorDisplay = ({ srcs }: Props) => {
	return (
		<div className="p-8 sm:p-16 justify-center gap-12 flex flex-wrap bg-radial from-zinc-900 to-background to-[75%]">
			{Array.from(srcs).map(([href, { src, alt }]) => (
				<a key={href} aria-label={alt} href={href} className="w-20 sm:w-24 group flex items-center justify-center">
					<img src={src} alt={alt} loading="lazy" className="aspect-square md:brightness-60 group-hover:brightness-100 transition-[filter,scale]" />
				</a>
			))}
		</div>
	)
}

export default SponsorDisplay
