// frontend/src/routes/admin/events/edit/+page.svelte
<script lang="ts">
	import { ZodError, type z } from 'zod';
	import EventForm from '../EventForm.svelte';
	import { goto } from '$app/navigation';
	import { toaster } from '$lib/toaster.svelte';

	import { updateEvent, type editEventForm } from '$lib/features/event/event';

	let { data } = $props();

	let errors = $state<z.typeToFlattenedError<z.infer<typeof editEventForm>>>();

	const handleSubmit = async (form: z.infer<typeof editEventForm>) => {
		try {
			await updateEvent(fetch, form, data.eventId);
			toaster.addToast('Event opdateret');
			goto('/admin/dashboard/events');
		} catch (e) {
			if (e instanceof ZodError) {
				errors = e.flatten();
				toaster.addToast('Kunne ikke redigere event', 'Noget gik galt...', 'error');
				return;
			}
			toaster.addToast('Kunne ikke redigere event', 'Noget gik galt...', 'error');
			throw e;
		}
	};
</script>

<main class="px-8 py-16 md:px-16">
	<h1 class="mb-8 text-4xl font-bold">Redigér event</h1>
	<EventForm
		event={data.event}
		{errors}
		venues={data.venues}
		artists={data.artists}
		onSubmit={handleSubmit}
	/>
</main>

// frontend/src/routes/admin/events/$eventId/edit.tsx
import { APIError } from '@/lib/api'
import EventForm from '@/lib/components/event-form/event-form'
import { useToast } from '@/lib/context/toast'
import { updateEvent, type editEventForm } from '@/lib/features/event'
import { useArtists, useEventById, useVenues } from '@/lib/features/hook'
import { useQueryClient } from '@tanstack/react-query'
import { createFileRoute, useNavigate } from '@tanstack/react-router'
import type { z } from 'zod'

export const Route = createFileRoute('/admin/events/$eventId/edit')({
  component: RouteComponent,
})

function RouteComponent() {
  const { eventId } = Route.useParams()
  const { addToast } = useToast()
  const queryClient = useQueryClient()
  const navigate = useNavigate()

  const eventQuery = useEventById(parseInt(eventId))
  const artistsQuery = useArtists()
  const venuesQuery = useVenues()

  const onSubmit = async (form: z.infer<typeof editEventForm>) => {
    try {
      await updateEvent(form, parseInt(eventId))
      addToast("Event opdateret")
      await queryClient.invalidateQueries({ queryKey: ["events", parseInt(eventId)] })
      navigate({ to: "/admin/events" })

    } catch (e) {
      if (e instanceof APIError) {
        addToast("Kunne ikke opdatere event", e.message, "error")
        return
      }

      addToast("Kunne ikke opdatere event", "Noget gik galt...", "error")
      throw e
    }
  }

  const isLoading = eventQuery.isLoading || artistsQuery.isLoading || venuesQuery.isLoading
  const isError = eventQuery.isError || artistsQuery.isError || venuesQuery.isError

  if (isLoading) return <p>Loading...</p>
  if (isError) return <p>Error...</p>

  return (
    <EventForm
      event={eventQuery.data}
      venues={venuesQuery.data?.records || []}
      artists={artistsQuery.data?.records || []}
      onSubmit={onSubmit}
    />
  )
}
