// frontend/src/routes/admin/dashboard/events/EventEntry.svelte
<script lang="ts">
	import { earliestConcert, latestConcert } from '$lib/concert';
	import type { Event } from '$lib/event';
	import { formatDateStr } from '$lib/time';
	import { format } from 'date-fns';
	import TrashIcon from '~icons/mdi/trash';

	type Props = {
		event: Event;
	};

	let { event }: Props = $props();

	const fromDate = $derived(earliestConcert(event.concerts)?.from || new Date());
	const toDate = $derived(latestConcert(event.concerts)?.to || new Date());
</script>

<a
	class="flex items-center gap-4 rounded-md border border-transparent p-2 hover:border-zinc-800 hover:bg-zinc-900"
	href="/admin/events/edit?id={event.id}"
>
	<span class="flex-1">{event.title}</span>
	<span class="line-clamp-1 flex-1 text-zinc-500"
		>{formatDateStr(fromDate)}, {format(fromDate, 'HH:mm')}</span
	>
	<span class="line-clamp-1 flex-1 text-zinc-500"
		>{formatDateStr(toDate)}, {format(toDate, 'HH:mm')}</span
	>
	<button class="text-zinc-400 hover:text-red-500">
		<TrashIcon />
	</button>
</a>

// frontend/app/routes/admin.dashboard.events/event-entry.tsx
import { format } from "date-fns";
import { BiTrash } from "react-icons/bi";
import { EventDTO } from "~/lib/event/event.dto";
import { formatDateString } from "~/lib/time/format";

type Props = {
  event: EventDTO;
  onDelete: () => void;
}

export const EventEntry = ({ event, onDelete }: Props) => {
  const { id, title, fromDate } = event;
  const formattedDate = `${formatDateString(fromDate)}, ${format(fromDate, "kk:mm")}`

  return (
    <div className="px-4 py-2 flex justify-between hover:bg-neutral-900">
      <a href={`/admin/event/rediger/${id}`} className="w-full flex">
        <span className="flex-1">{title}</span>
        <span className="flex-1">{formattedDate}</span>
      </a>
      <button className="text-lg hover:text-red-500" onClick={onDelete}><BiTrash /></button>
    </div>
  )
}
